/**
 * WSZYSTKIE teksty interfejsu. Zero polskich stringów w JSX (CLAUDE.md, zasada 7).
 * Bez pauz i półpauz: wyłącznie zwykły myślnik. Pilnuje tego tests/unit/copy.test.ts.
 * Do klienta mówimy na Ty, bez żargonu, komunikaty błędów mówią, co zrobić.
 */
export const copy = {
  marka: {
    nazwa: "Foodie Media",
    panel: "Panel klienta Foodie Media",
    opisOg: "Panel klienta Foodie Media",
    panelZespolu: "Panel zespołu Foodie Media",
  },
  start: {
    tytul: "Panel klienta Foodie Media",
    opis: "Tu akceptujesz materiały na kolejny miesiąc, sprawdzasz harmonogram publikacji, raporty i faktury.",
    jakWejsc: "Wejdź z linku, który dostałeś od swojego opiekuna. Link i PIN są tylko dla Ciebie.",
    pomoc: "Nie masz linku albo nie działa? Napisz do swojego opiekuna w Foodie Media.",
    zespol: "Jesteś z zespołu Foodie Media?",
    zespolLink: "Zaloguj się do panelu zespołu",
  },
  pin: {
    tytul: "Wpisz PIN",
    opis: "PIN dostałeś razem z linkiem od swojego opiekuna w Foodie Media.",
    etykieta: "PIN",
    zapamietaj: "Zapamiętaj mnie na tym urządzeniu",
    przycisk: "Wejdź do panelu",
    trwa: "Sprawdzamy...",
    blad: "Nie udało się wejść. Sprawdź, czy otwierasz właściwy link i wpisujesz właściwy PIN. Jeśli to się powtarza, napisz do swojego opiekuna.",
    limit: "Za dużo prób w krótkim czasie. Odczekaj chwilę i spróbuj ponownie.",
  },
  nawigacja: {
    start: "Start",
    materialy: "Materiały do akceptacji",
    harmonogram: "Harmonogram",
    archiwum: "Archiwum materiałów",
    raporty: "Raporty",
    faktury: "Faktury i dokumenty",
    pakiet: "Twój pakiet",
    uslugi: "Co jeszcze możemy zrobić",
    wdrozenie: "Wdrożenie",
    wkrotce: "wkrótce",
    wyloguj: "Wyloguj",
    zalogowanyJako: "Zalogowano jako",
  },
  klientStart: {
    powitanie: "Cześć",
    doAkceptacji: "Czeka na Twoją akceptację",
    przejrzyj: "Przejrzyj materiały",
    autoAkceptacja: "Automatyczna akceptacja",
    autoWylaczona: "Bez automatycznej akceptacji",
    wersja: "wersja",
    naBiezaco: "Wszystko na bieżąco",
    naBiezacoOpis: "Nie ma materiałów do akceptacji. Gdy przygotujemy kolejny miesiąc, zobaczysz to tutaj i dostaniesz wiadomość od opiekuna.",
    posty: { jeden: "post", kilka: "posty", wiele: "postów" },
    relacje: { jeden: "relacja", kilka: "relacje", wiele: "relacji" },
    kampanie: { jeden: "kampania reklamowa", kilka: "kampanie reklamowe", wiele: "kampanii reklamowych" },
  },
  materialy: {
    wBudowie: "Ekran akceptacji materiałów powstaje w kolejnym etapie. Na razie zobaczysz tu podsumowanie pakietu.",
    wroc: "Wróć na start",
    status: {
      szkic: "Szkic",
      do_akceptacji: "Do akceptacji",
      poprawki: "Poprawki",
      zaakceptowany: "Zaakceptowany",
      zaplanowany: "Zaplanowany",
    },
  },
  stopka: {
    regulamin: "Regulamin",
    prywatnosc: "Polityka prywatności",
    prawa: "Foodie Media",
  },
  nieZnaleziono: {
    tytul: "Nie ma takiej strony",
    opis: "Sprawdź link, który dostałeś od opiekuna, albo wróć na stronę główną.",
    wroc: "Wróć na stronę główną",
  },
  zespol: {
    logowanie: {
      tytul: "Panel zespołu",
      opis: "Zaloguj się adresem e-mail. Wyślemy Ci sześciocyfrowy kod.",
      email: "Adres e-mail",
      wyslijKod: "Wyślij kod",
      wysylanie: "Wysyłamy...",
      kodWyslany: "Jeśli ten adres jest na liście zespołu, wysłaliśmy na niego kod. Sprawdź skrzynkę i wpisz go poniżej.",
      kod: "Kod z e-maila",
      zaloguj: "Zaloguj się",
      sprawdzanie: "Sprawdzamy...",
      zlyKod: "Kod się nie zgadza albo wygasł. Wyślij nowy kod i spróbuj ponownie.",
      innyAdres: "Użyj innego adresu",
      zbytWiele: "Za dużo prób. Odczekaj chwilę i spróbuj ponownie.",
    },
    nawigacja: {
      pulpit: "Pulpit",
      klienci: "Klienci",
      ustawienia: "Ustawienia",
      wyloguj: "Wyloguj",
    },
    role: {
      admin: "Admin",
      csm: "Opiekun klienta",
      content_creator: "Content creator",
      media_buyer: "Media buyer",
      sales: "Sprzedaż",
    },
    kategorie: {
      kat1: "Kategoria 1: osobne restauracje",
      kat2: "Kategoria 2: sieć, jeden profil",
      kat3: "Kategoria 3: sieć, osobne profile",
    },
    kategorieKrotko: { kat1: "kat. 1", kat2: "kat. 2", kat3: "kat. 3" },
    pakiety: { foodie_one: "Foodie One", foodie_360: "Foodie 360°", siec: "Sieć" },
    pulpit: {
      tytul: "Pulpit",
      opis: "Klienci, których obsługujesz, i to, co u nich czeka.",
      brakKlientow: "Nie masz jeszcze przypisanych klientów. Poproś admina o przypisanie.",
      kolumny: { klient: "Klient", kategoria: "Kategoria", pakiet: "Pakiet", doAkceptacji: "Do akceptacji", linki: "Aktywne linki" },
      otworz: "Otwórz kartę",
      miesiecznie: "mies. netto",
    },
    karta: {
      lokale: "Lokale",
      kontakty: "Osoby kontaktowe",
      slack: "Slack",
      opiekun: "Opiekun",
      brakOpiekuna: "nie przypisano",
      wspolpracaOd: "Współpraca od",
      zakladki: {
        materialy: "Materiały",
        harmonogram: "Harmonogram",
        raporty: "Raporty",
        faktury: "Faktury",
        dokumenty: "Dokumenty",
        dostep: "Dostęp",
        ustawienia: "Ustawienia",
      },
      wkrotce: "Ta zakładka powstaje w kolejnym etapie.",
      podsumowanie: "Podsumowanie",
    },
    dostep: {
      tytul: "Dostęp klienta",
      opis: "Każda osoba po stronie klienta dostaje własny link i PIN. Dzięki temu widzisz, kto zaakceptował materiały.",
      utworz: "Utwórz link",
      brakLinkow: "Ten klient nie ma jeszcze żadnego linku. Utwórz pierwszy.",
      kolumny: { osoba: "Osoba", utworzono: "Utworzono", ostatnieWejscie: "Ostatnie wejście", status: "Status", urzadzenia: "Urządzenia" },
      status: { aktywny: "Aktywny", wygaszony: "Wygaszony", zablokowany: "Zablokowany do", tylkoPodglad: "tylko podgląd" },
      nigdy: "jeszcze nie",
      akcje: {
        kopiujLink: "Kopiuj link",
        wygas: "Wygaś link",
        wygasPotwierdz: "Wygasić ten link? Osoba straci dostęp przy następnym wejściu. Tego nie da się cofnąć.",
        wylogujUrzadzenia: "Wyloguj wszystkie urządzenia",
        wylogujPotwierdz: "Wylogować wszystkie urządzenia tego linku? Osoba będzie musiała ponownie wpisać PIN.",
        resetujPin: "Zresetuj PIN",
        resetujPotwierdz: "Zresetować PIN? Stary PIN przestanie działać, a wszystkie urządzenia zostaną wylogowane. Nowy PIN zobaczysz tylko raz.",
      },
      nowy: {
        tytul: "Nowy link dostępu",
        osoba: "Osoba kontaktowa",
        innaOsoba: "Inna osoba (wpisz opis)",
        etykieta: "Opis linku",
        etykietaPodpowiedz: "np. Marek - właściciel",
        rodzajPinu: "Rodzaj PIN-u",
        pin4: "4 cyfry (domyślnie)",
        pin6: "6 cyfr",
        haslo: "Proste hasło",
        mozeAkceptowac: "Ta osoba może akceptować materiały",
        tylkoPodgladOpis: "Bez zaznaczenia: link tylko do podglądu i komentarzy, bez przycisków decyzji.",
        utworz: "Utwórz",
        tworzenie: "Tworzymy...",
        anuluj: "Anuluj",
      },
      gotowy: {
        tytul: "Link i PIN gotowe",
        opis: "PIN widzisz tylko teraz. Skopiuj oba pola i przekaż je klientowi tak, jak zwykle (np. na WhatsAppie). Wiadomość piszesz sam.",
        link: "Link",
        pin: "PIN",
        kopiuj: "Kopiuj",
        skopiowano: "Skopiowano",
        kopiujOba: "Kopiuj link i PIN",
        zamknij: "Zamknij",
        nowyPinTytul: "Nowy PIN",
        nowyPinOpis: "Stary PIN przestał działać, urządzenia zostały wylogowane. Nowy PIN widzisz tylko teraz.",
      },
      historia: {
        tytul: "Historia logowań",
        brak: "Jeszcze nic się nie wydarzyło.",
        kolumny: { kiedy: "Kiedy", co: "Zdarzenie", kto: "Link" },
        zdarzenia: {
          "klient.logowanie_ok": "Udane logowanie",
          "klient.logowanie_blad": "Nieudana próba logowania",
          "klient.blokada_24h": "Blokada linku na 24 godziny (10 nieudanych prób)",
          "klient.wylogowanie": "Wylogowanie",
          "klient.plik_pobrany": "Pobranie pliku",
          "link.utworzony": "Utworzono link",
          "link.wygaszony": "Wygaszono link",
          "link.pin_zresetowany": "Zresetowano PIN",
          "link.urzadzenia_wylogowane": "Wylogowano wszystkie urządzenia",
          "link.skopiowany": "Skopiowano dostęp",
        },
      },
      bledy: {
        brakEtykiety: "Wpisz opis linku albo wybierz osobę kontaktową.",
        ogolny: "Nie udało się wykonać tej operacji. Odśwież stronę i spróbuj ponownie.",
      },
    },
    faktury: {
      tytul: "Faktury",
      wkrotce: "Faktury dochodzą w kolejnym etapie.",
    },
    ustawienia: {
      tytul: "Ustawienia",
      zespol: {
        tytul: "Zespół",
        opis: "Tylko osoby z tej listy mogą zalogować się do panelu zespołu. Dodanie osoby tworzy jej konto; kod logowania dostaje na e-mail przy pierwszym wejściu.",
        dodaj: "Dodaj osobę",
        imie: "Imię",
        email: "Adres e-mail",
        rola: "Rola",
        dodawanie: "Dodajemy...",
        kolumny: { osoba: "Osoba", email: "E-mail", rola: "Rola", status: "Status" },
        aktywny: "Aktywny",
        nieaktywny: "Nieaktywny",
        dezaktywuj: "Dezaktywuj",
        aktywuj: "Aktywuj",
        bledy: {
          dane: "Uzupełnij imię, poprawny adres e-mail i rolę.",
          istnieje: "Osoba z tym adresem już jest na liście.",
          ogolny: "Nie udało się dodać osoby. Spróbuj ponownie.",
          allowlista: "Ten adres nie przechodzi filtra domen (TEAM_EMAIL_ALLOWLIST). Dopisz domenę albo adres do zmiennej środowiskowej.",
        },
      },
    },
  },
  regulamin: {
    tytul: "Regulamin panelu klienta",
    wstep: "Ten regulamin opisuje zasady korzystania z panelu klienta Foodie Media pod adresem panel.foodiemedia.pl.",
    doUzupelnienia: "Treść tej sekcji uzupełni Foodie Media przed uruchomieniem panelu dla klientów.",
    sekcje: [
      { naglowek: "1. Postanowienia ogólne", tresc: [] },
      { naglowek: "2. Dostęp do panelu", tresc: ["Dostęp do panelu odbywa się przez indywidualny link i PIN przekazane przez opiekuna. Link i PIN są przeznaczone dla osoby, której zostały przekazane."] },
      { naglowek: "3. Akceptacja materiałów", tresc: ["Klient akceptuje pakiet materiałów na dany miesiąc jednym przyciskiem albo zgłasza uwagi do poszczególnych materiałów."] },
      { naglowek: "4. Automatyczna akceptacja", tresc: ["Jeżeli w ciągu 72 godzin od wysłania materiałów do akceptacji klient nie zaakceptuje ich ani nie zgłosi uwag, materiały uznaje się za zaakceptowane automatycznie. Licznik jest widoczny w panelu od chwili wysłania materiałów, a na 24 godziny przed terminem panel wyświetla ostrzeżenie. Zgłoszenie uwag zatrzymuje licznik."] },
      { naglowek: "5. Komentarze i uwagi", tresc: [] },
      { naglowek: "6. Dane osobowe", tresc: [] },
      { naglowek: "7. Postanowienia końcowe", tresc: [] },
    ],
  },
  prywatnosc: {
    tytul: "Polityka prywatności",
    wstep: "Panel przetwarza wyłącznie dane osób kontaktowych po stronie klienta: imię i nazwisko, telefon i adres e-mail. Nie zbieramy danych gości restauracji.",
    doUzupelnienia: "Treść tej sekcji uzupełni Foodie Media przed uruchomieniem panelu dla klientów.",
    sekcje: [
      { naglowek: "1. Administrator danych", tresc: [] },
      { naglowek: "2. Jakie dane przetwarzamy i po co", tresc: [] },
      { naglowek: "3. Gdzie przechowujemy dane", tresc: ["Dane są przechowywane na serwerach w Unii Europejskiej (Frankfurt)."] },
      { naglowek: "4. Jak długo przechowujemy dane", tresc: ["Materiały przechowujemy przez 24 miesiące, dziennik zdarzeń przez 12 miesięcy."] },
      { naglowek: "5. Pliki cookies", tresc: ["Panel używa wyłącznie technicznych plików cookies niezbędnych do utrzymania sesji. Nie używamy analityki zewnętrznej ani cookies marketingowych."] },
      { naglowek: "6. Twoje prawa", tresc: [] },
    ],
  },
  bledy: {
    ogolny: "Coś poszło nie tak. Odśwież stronę, a jeśli to nie pomoże, napisz do swojego opiekuna.",
  },
} as const;

export type Copy = typeof copy;
