/**
 * WSZYSTKIE teksty interfejsu. Zero polskich stringów w JSX (CLAUDE.md, zasada 7).
 * Bez pauz i półpauz: wyłącznie zwykły myślnik. Pilnuje tego tests/unit/copy.test.ts.
 * Do klienta mówimy na Ty, bez żargonu, komunikaty błędów mówią, co zrobić.
 */
export const copy = {
  marka: {
    nazwa: "Foodie Media",
    panel: "Panel klienta Foodie Media",
    opisOg: "Panel klienta Foodie Media",
    panelZespolu: "Panel zespołu Foodie Media",
  },
  start: {
    tytul: "Panel klienta Foodie Media",
    opis: "Tu akceptujesz materiały na kolejny miesiąc, sprawdzasz harmonogram publikacji, raporty i faktury.",
    jakWejsc: "Wejdź z linku, który dostałeś od swojego opiekuna. Link i PIN są tylko dla Ciebie.",
    pomoc: "Nie masz linku albo nie działa? Napisz do swojego opiekuna w Foodie Media.",
    zespol: "Jesteś z zespołu Foodie Media?",
    zespolLink: "Zaloguj się do panelu zespołu",
  },
  pin: {
    tytul: "Wpisz PIN",
    opis: "PIN dostałeś razem z linkiem od swojego opiekuna w Foodie Media.",
    etykieta: "PIN",
    zapamietaj: "Zapamiętaj mnie na tym urządzeniu",
    przycisk: "Wejdź do panelu",
    trwa: "Sprawdzamy...",
    blad: "Nie udało się wejść. Sprawdź, czy otwierasz właściwy link i wpisujesz właściwy PIN. Jeśli to się powtarza, napisz do swojego opiekuna.",
    limit: "Za dużo prób w krótkim czasie. Odczekaj chwilę i spróbuj ponownie.",
  },
  nawigacja: {
    start: "Start",
    materialy: "Materiały do akceptacji",
    harmonogram: "Harmonogram",
    archiwum: "Archiwum materiałów",
    raporty: "Raporty",
    faktury: "Faktury i dokumenty",
    pakiet: "Twój pakiet",
    uslugi: "Co jeszcze możemy zrobić",
    wdrozenie: "Wdrożenie",
    wkrotce: "wkrótce",
    wyloguj: "Wyloguj",
    zalogowanyJako: "Zalogowano jako",
  },
  klientStart: {
    powitanie: "Cześć",
    doAkceptacji: "Czeka na Twoją akceptację",
    przejrzyj: "Przejrzyj materiały",
    autoAkceptacja: "Automatyczna akceptacja",
    autoWylaczona: "Bez automatycznej akceptacji",
    wersja: "wersja",
    naBiezaco: "Wszystko na bieżąco",
    naBiezacoOpis: "Nie ma materiałów do akceptacji. Gdy przygotujemy kolejny miesiąc, zobaczysz to tutaj i dostaniesz wiadomość od opiekuna.",
    posty: { jeden: "post", kilka: "posty", wiele: "postów" },
    relacje: { jeden: "relacja", kilka: "relacje", wiele: "relacji" },
    kampanie: { jeden: "kampania reklamowa", kilka: "kampanie reklamowe", wiele: "kampanii reklamowych" },
  },
  materialy: {
    wBudowie: "Ekran akceptacji materiałów powstaje w kolejnym etapie. Na razie zobaczysz tu podsumowanie pakietu.",
    wroc: "Wróć na start",
    status: {
      szkic: "Szkic",
      do_akceptacji: "Do akceptacji",
      poprawki: "Poprawki",
      zaakceptowany: "Zaakceptowany",
      zaplanowany: "Zaplanowany",
    },
  },
  /** Podsumowania zdarzeń do Zapiera (SPEC rozdz. 15). Zmienne: {klient}, {okres}, {osoba}, {wersja}, {uwagi}, {powod}. */
  zdarzenia: {
    system: "panel (automatycznie)",
    podsumowanie: {
      "pakiet.wyslany": "Materiały {klient} na {okres} wysłane do akceptacji (wersja {wersja}) przez {osoba}.",
      "pakiet.otwarty": "{osoba} ({klient}) otworzył(a) materiały na {okres} pierwszy raz.",
      "pakiet.zaakceptowany": "{osoba} ({klient}) zaakceptował(a) materiały na {okres}.",
      "pakiet.zaakceptowany_auto": "Materiały {klient} na {okres} zostały zaakceptowane automatycznie po upływie terminu.",
      "pakiet.poprawki": "{osoba} ({klient}) zgłosił(a) uwagi do materiałów na {okres}. Liczba uwag: {uwagi}.",
      "pakiet.nieotwarty_po_24h": "{klient} nie otworzył(a) materiałów na {okres} przez 24 godziny od wysyłki.",
      "pakiet.auto_za_24h": "Do automatycznej akceptacji materiałów {klient} na {okres} zostały 24 godziny.",
      "pakiet.auto_wstrzymana_uwagi": "Termin auto-akceptacji materiałów {klient} na {okres} minął, ale klient ma nierozwiązane uwagi ({uwagi}). Odpowiedz na nie i oznacz jako załatwione.",
      "pakiet.wycofany": "Materiały {klient} na {okres} wycofane do szkicu przez {osoba}.",
      "pakiet.cofniety_do_poprawek": "Zaakceptowane materiały {klient} na {okres} cofnięte do poprawek przez {osoba}. Powód: {powod}",
      "komentarz.po_akceptacji": "{osoba} ({klient}) dodał(a) uwagę po akceptacji materiałów na {okres}.",
      "material.podmieniony_po_akceptacji": "W zaakceptowanych materiałach {klient} na {okres} podmieniono materiał ({osoba}).",
    },
  },
  /** Walidacja przed wysyłką do akceptacji (SPEC rozdz. 8): braki blokują, ostrzeżenia nie. */
  wysylka: {
    brakDaty: "{tytul}: brak daty publikacji",
    bezMaterialow: "Pakiet nie ma żadnych materiałów.",
    bezKampanii: "Pakiet nie ma żadnej kampanii reklamowej. Wysyłka jest możliwa, ale sprawdź, czy to zamierzone.",
    typ: { post: "Post", relacja: "Relacja", reels: "Reels", reklama: "Reklama" },
  },
  /** Odmowy maszyny stanów (SPEC rozdz. 6.8), pokazywane osobie, która kliknęła. */
  przejscia: {
    odmowa: {
      niedozwolone_ze_statusu: "Ta zmiana nie jest możliwa w obecnym statusie pakietu. Odśwież stronę.",
      niewlasciwy_aktor: "Nie masz uprawnień do tej zmiany.",
      link_tylko_do_podgladu: "Twój link pozwala oglądać i komentować materiały. Akceptację zostaw osobie z pełnym dostępem.",
      brak_uwag: "Napisz najpierw, co poprawić - kliknij komentarz przy materiale.",
      brak_powodu: "Wpisz powód cofnięcia. Klient zobaczy go w panelu.",
      auto_wylaczona: "Ten pakiet ma wyłączoną automatyczną akceptację.",
      termin_nie_minal: "Termin automatycznej akceptacji jeszcze nie minął.",
      nierozwiazane_uwagi: "Klient ma nierozwiązane uwagi. Odpowiedz na nie i oznacz jako załatwione albo cofnij pakiet do poprawek.",
      braki_w_materialach: "Uzupełnij braki przed wysyłką.",
      nie_znaleziono: "Nie znaleziono pakietu. Odśwież stronę.",
      konflikt: "Ktoś w międzyczasie zmienił status pakietu. Odśwież stronę i sprawdź, co się zmieniło.",
    },
  },
  /** Ramki podglądów 1:1 (SPEC rozdz. 7). Neutralne teksty interfejsu Facebooka i Instagramu, bez logotypów Meta. */
  podglad: {
    facebook: "Facebook",
    instagram: "Instagram",
    sponsorowane: "Sponsorowane",
    publiczne: "Publiczne",
    zobaczWiecej: "Zobacz więcej",
    lubieTo: "Lubię to!",
    komentarz: "Komentarz",
    udostepnij: "Udostępnij",
    reakcje: "Ty i 41 innych osób",
    komentarze: "3 komentarze",
    udostepnienia: "2 udostępnienia",
    odpowiedz: "Odpowiedz...",
    godzinTemu: "2 godz.",
    obserwuj: "Obserwuj",
    oryginalnyDzwiek: "Oryginalny dźwięk",
    przesunWGore: "Przesuń w górę",
    reels: "Reels",
    wideoWyciszone: "Wideo jest domyślnie wyciszone. Dźwięk włączysz kontrolką odtwarzacza.",
    publikacja: "Publikacja:",
    bezDaty: "bez daty publikacji",
    strona: "Strona",
    slajd: "Slajd {n} z {liczba}",
    poprzedni: "Poprzedni",
    nastepny: "Następny",
    relacja: "Relacja {n} z {liczba}",
    gdzieZobaczysz: "Gdzie zobaczysz reklamę",
    miejsca: {
      fb_kanal_telefon: "Kanał na telefonie",
      fb_kanal_komputer: "Kanał na komputerze",
      fb_relacje: "Relacje",
      fb_reels: "Reels",
      ig_kanal: "Kanał",
      ig_relacje_reels: "Relacje i Reels",
    },
    brakIg: {
      klient: "Podgląd na Instagramie pojawi się, gdy Twój opiekun uzupełni nick na Instagramie.",
      zespol: "Uzupełnij nick na Instagramie w karcie klienta, żeby zobaczyć podgląd na Instagramie.",
    },
    warianty: {
      grafika: "Grafika",
      tekst: "Tekst",
      naglowek: "Nagłówek",
      lokal: "Lokal",
      z: "z",
      wszystkieLokale: "Wszystkie lokale (wersja wspólna)",
      kombinacje: "Możesz obejrzeć każdą z {n} kombinacji.",
    },
    elementy: { grafika: "grafika", tekst: "tekst", naglowek: "nagłówek", opis: "opis", cta: "przycisk", link: "link" },
    zrodla: {
      wszystkoWspolne: "Wszystkie elementy tej reklamy są wspólne dla wszystkich lokali.",
      wersjaDlaLokalu: "Wersja dla {lokal}: {elementy}.",
      wspolne: "Wspólne dla wszystkich lokali: {elementy}.",
    },
    wszystkieWarianty: "Zobacz wszystkie warianty",
    ukryjWarianty: "Ukryj wszystkie warianty",
    wszystkieLokalePodpis: "wszystkie lokale",
    grafiki: "Grafiki",
    teksty: "Teksty",
    naglowki: "Nagłówki",
    pozostale: "Opis, przycisk i link",
    ctaDomyslne: "Więcej informacji",
    /** Zamknięta lista przycisków reklamy (SPEC rozdz. 7.4, plan W2): podgląd pokazuje dokładnie ten przycisk, który pokaże Facebook. */
    cta: ["Więcej informacji", "Zarezerwuj", "Zamów teraz", "Wyślij wiadomość", "Polub stronę", "Kup teraz", "Zarejestruj się", "Skontaktuj się", "Zadzwoń", "Pobierz"],
    domenaZastepcza: "twojastrona.pl",
    cele: { sprzedaz: "Sprzedaż", ruch: "Ruch na stronie", polubienia: "Polubienia strony", leady: "Zapytania i rezerwacje", zasieg: "Zasięg", inne: "Inne" },
  },
  /** Ekran pakietu (SPEC rozdz. 6): ten sam dla klienta i podglądu zespołu. */
  pakiet: {
    wersja: "wersja",
    zakladki: { posty: "Posty", relacje: "Relacje", kampanie: "Kampanie", wszystko: "Wszystko" },
    noweOdpowiedzi: "{n} nowe odpowiedzi zespołu",
    obejrzano: "Obejrzano {x} z {y}",
    autoAkceptacja: "Automatyczna akceptacja",
    autoOstatniaDoba: "Zostało 24 godziny",
    autoMinela: "Termin automatycznej akceptacji minął. Czekamy na decyzję zespołu.",
    autoWylaczona: "Bez automatycznej akceptacji",
    licznikZatrzymany: "Licznik automatycznej akceptacji zatrzymany",
    tylkoPodglad: "Twój link pozwala oglądać i komentować materiały. Decyzję podejmie osoba z pełnym dostępem.",
    decyzje: { uwagi: "Zgłaszam uwagi", akceptuj: "Akceptuję wszystko" },
    modalAkceptacji: {
      tytul: "Akceptujesz cały miesiąc",
      opis: "Akceptujesz {posty}, {relacje} i {kampanie}. Zaplanujemy publikację zgodnie z harmonogramem.",
      sprawdzilem: "Sprawdziłem daty publikacji",
      zaznaczDaty: "Zaznacz, że sprawdziłeś daty publikacji.",
      ostrzezenieUwagi: "Masz {n} nierozwiązane uwagi. Akceptacja oznacza, że mimo nich ruszamy z publikacją.",
      potwierdz: "Tak, akceptuję",
      anuluj: "Wróć do materiałów",
      trwa: "Zapisujemy...",
    },
    modalUwag: {
      tytul: "Zgłaszasz uwagi",
      opis: "Przekażemy zespołowi Twoje uwagi ({n}). Licznik automatycznej akceptacji się zatrzyma, a materiały wrócą do Ciebie w poprawionej wersji.",
      potwierdz: "Wyślij uwagi",
      anuluj: "Wróć",
      trwa: "Wysyłamy...",
    },
    banery: {
      zaakceptowano: "Zaakceptowano {data} przez {osoba}.",
      zaakceptowanoAuto: "Materiały zostały zatwierdzone automatycznie {data}, zgodnie z zasadami panelu. Nadal możesz dodać uwagi - sprawdzimy je przed publikacją.",
      komentowanieWlaczone: "Nadal możesz dodać uwagi do każdego materiału.",
      poprawki: "Przekazaliśmy uwagi zespołowi. Odezwiemy się z poprawioną wersją.",
      cofniecie: "Cofnęliśmy akceptację {data}: {powod}. Sprawdź poprawione materiały.",
      podmiana: "Po akceptacji podmieniliśmy materiały. Są oznaczone plakietką.",
      zaplanowano: "Publikacje są zaplanowane zgodnie z harmonogramem.",
      szkic: "Ten miesiąc jest jeszcze w przygotowaniu.",
    },
    plakietki: { poprawione: "Poprawione", nowe: "Nowe", reels: "Reels", uwagaPoAkceptacji: "Uwaga po akceptacji", zalatwione: "Załatwione", nieprzeczytane: "Nowa odpowiedź", nieprzeczytanaUwaga: "Nowa uwaga" },
    komentarze: {
      tytul: "Uwagi i odpowiedzi",
      brak: "Nie ma jeszcze uwag do tego materiału.",
      dodaj: "Dodaj uwagę",
      doPakietu: "Uwaga do całego miesiąca",
      doPakietuOpis: "Coś, co dotyczy wszystkich materiałów, nie jednego posta.",
      podpowiedz: "Napisz, co poprawić. Konkretnie: który element i jak ma wyglądać.",
      wyslij: "Wyślij uwagę",
      wysylanie: "Wysyłamy...",
      anuluj: "Anuluj",
      licznik: "{n} / 4000",
      historia: "Historia uwag (runda {n})",
      odpowiedzZespolu: "Odpowiedź zespołu",
      doCzego: "Do czego",
      calaReklama: "Cała reklama",
      taGrafika: "Ta grafika",
      tenTekst: "Ten tekst",
      tenNaglowek: "Ten nagłówek",
      dotyczy: "Dotyczy: {co}",
      blad: "Nie udało się zapisać uwagi. Spróbuj ponownie.",
      pusty: "Wpisz treść uwagi.",
      zaDlugi: "Uwaga może mieć najwyżej 4000 znaków.",
    },
    kampania: { cel: "Cel:", ktora: "Kampania {n} z {liczba}" },
    lista: {
      tytul: "Materiały do akceptacji",
      opis: "Materiały na kolejne miesiące i to, co już zaakceptowałeś.",
      brak: "Nie ma teraz materiałów do akceptacji.",
      otworz: "Otwórz",
    },
    zespolWidziKlienta: "Tak widzi ten ekran klient. Przyciski decyzji są u klienta, tu masz akcje zespołu poniżej.",
  },
  /** Harmonogram klienta (SPEC rozdz. 5.3, 8): ten sam kalendarz, tylko do odczytu, z komentarzem przy materiale. */
  harmonogram: {
    tytul: "Harmonogram",
    opis: "Daty publikacji postów i relacji. Kampanie reklamowe nie mają daty: ruszają po akceptacji.",
    poprzedni: "Poprzedni miesiąc",
    nastepny: "Następny miesiąc",
    brak: "Nie ma zaplanowanych publikacji w tym miesiącu.",
    lista: "Lista publikacji",
    kampanie: "Kampanie w tym miesiącu",
    bezKampanii: "W tym miesiącu nie ma kampanii reklamowej.",
    skomentuj: "Skomentuj",
    zobacz: "Zobacz",
    bezDaty: "Jeszcze bez daty",
    dniTygodnia: ["Pn", "Wt", "Śr", "Cz", "Pt", "So", "Nd"],
    statusy: { szkic: "szkic", do_akceptacji: "do akceptacji", poprawki: "poprawki", zaakceptowany: "zaakceptowany", zaplanowany: "zaplanowany" },
    typ: { post: "Post", relacja: "Relacja", reels: "Reels", reklama: "Reklama" },
    cel: "Cel:",
  },
  /** „Zobacz jak klient" (SPEC rozdz. 2, kryterium 25): stały pasek, tryb wyłącznie do odczytu. */
  podgladKlienta: {
    przycisk: "Zobacz jak klient",
    pasek: "PODGLĄD KLIENTA - {nazwa}",
    pasekOpis: "Widzisz panel tak, jak widzi go klient. Nic tu nie zapiszesz.",
    wyjdz: "Wyjdź",
    niedostepne: "niedostępne w podglądzie",
    decyzjeZablokowane: "Przyciski decyzji są niedostępne w podglądzie. Decyzję podejmuje klient.",
    komentarzeZablokowane: "W podglądzie nie da się dodać uwagi. Odpowiedzi klientowi wysyłasz z panelu zespołu.",
    zalogowanyJako: "Podgląd zespołu",
    blad: "Podgląd klienta jest dostępny wyłącznie w trybie odczytu.",
  },
  stopka: {
    regulamin: "Regulamin",
    prywatnosc: "Polityka prywatności",
    prawa: "Foodie Media",
  },
  nieZnaleziono: {
    tytul: "Nie ma takiej strony",
    opis: "Sprawdź link, który dostałeś od opiekuna, albo wróć na stronę główną.",
    wroc: "Wróć na stronę główną",
  },
  zespol: {
    logowanie: {
      tytul: "Panel zespołu",
      opis: "Zaloguj się adresem e-mail. Wyślemy Ci kod, który wpiszesz poniżej.",
      email: "Adres e-mail",
      wyslijKod: "Wyślij kod",
      wysylanie: "Wysyłamy...",
      kodWyslany: "Jeśli ten adres jest na liście zespołu, wysłaliśmy na niego kod. Sprawdź skrzynkę i wpisz go poniżej.",
      kod: "Kod z e-maila",
      zaloguj: "Zaloguj się",
      sprawdzanie: "Sprawdzamy...",
      zlyKod: "Kod się nie zgadza albo wygasł. Przepisz wszystkie cyfry z maila albo wyślij nowy kod.",
      innyAdres: "Użyj innego adresu",
      zbytWiele: "Za dużo prób. Odczekaj chwilę i spróbuj ponownie.",
      brakDostepu: "Ten adres nie ma dostępu do panelu zespołu. Zostałeś wylogowany. Jeśli to pomyłka, poproś admina o dodanie Cię do zespołu.",
    },
    nawigacja: {
      pulpit: "Pulpit",
      klienci: "Klienci",
      skrzynka: "Skrzynka uwag",
      ustawienia: "Ustawienia",
      wyloguj: "Wyloguj",
    },
    role: {
      admin: "Admin",
      csm: "Opiekun klienta",
      content_creator: "Content creator",
      media_buyer: "Media buyer",
      sales: "Sprzedaż",
    },
    kategorie: {
      kat1: "Kategoria 1: osobne restauracje",
      kat2: "Kategoria 2: sieć, jeden profil",
      kat3: "Kategoria 3: sieć, osobne profile",
    },
    kategorieKrotko: { kat1: "kat. 1", kat2: "kat. 2", kat3: "kat. 3" },
    pakiety: { foodie_one: "Foodie One", foodie_360: "Foodie 360°", siec: "Sieć" },
    pulpit: {
      tytul: "Pulpit",
      opis: "Klienci, których obsługujesz, i to, co u nich czeka.",
      brakKlientow: "Nie masz jeszcze przypisanych klientów. Poproś admina o przypisanie.",
      kolumny: { klient: "Klient", kategoria: "Kategoria", pakiet: "Pakiet", doAkceptacji: "Do akceptacji", linki: "Aktywne linki" },
      otworz: "Otwórz kartę",
      miesiecznie: "mies. netto",
    },
    karta: {
      demo: "klient demonstracyjny",
      lokale: "Lokale",
      kontakty: "Osoby kontaktowe",
      slack: "Slack",
      opiekun: "Opiekun",
      brakOpiekuna: "nie przypisano",
      wspolpracaOd: "Współpraca od",
      zakladki: {
        materialy: "Materiały",
        harmonogram: "Harmonogram",
        raporty: "Raporty",
        faktury: "Faktury",
        dokumenty: "Dokumenty",
        dostep: "Dostęp",
        ustawienia: "Ustawienia",
      },
      wkrotce: "Ta zakładka powstaje w kolejnym etapie.",
      podsumowanie: "Podsumowanie",
    },
    pulpitPakiety: {
      tytul: "Pakiety w toku",
      opis: "Wszystkie pakiety poza zaplanowanymi. Pakiet z wstrzymaną auto-akceptacją ma osobny, bursztynowy wiersz.",
      brak: "Żaden pakiet nie czeka na decyzję.",
      kolumny: { klient: "Klient", miesiac: "Miesiąc", status: "Status", wyslano: "Wysłano", czeka: "Czeka", auto: "Auto-akcept za", uwagi: "Uwagi", akcja: "Akcja" },
      wstrzymana: "Auto-akceptacja wstrzymana",
      nieprzeczytane: "{n} nieprzeczytane",
      nierozwiazane: "{n} nierozwiązane",
      bezUwag: "0",
      odpowiedz: "Odpowiedz na uwagi",
      otworz: "Otwórz pakiet",
      temu: "{czas} temu",
      dni: { jeden: "dzień", kilka: "dni", wiele: "dni" },
      godziny: { jeden: "godz.", kilka: "godz.", wiele: "godz." },
      auto: { za: "za", minal: "minął", zatrzymane: "zatrzymane", wylaczona: "wyłączona", brak: "-" },
      filtry: {
        zakres: "Zakres",
        moi: "Moi klienci",
        wszyscy: "Wszyscy klienci",
        status: "Status",
        wszystkieStatusy: "Wszystkie statusy",
        miesiac: "Miesiąc",
        wszystkieMiesiace: "Wszystkie miesiące",
        pokaz: "Pokaż",
        wyczysc: "Wyczyść",
      },
      pokazLink: "Pokaż link",
      pokazLinkTytul: "Link dostępu klienta",
      pokazLinkOpis: "Wybierz osobę. Każde pokazanie linku zapisuje się w historii dostępu.",
      pokazLinkBrak: "Ten klient nie ma aktywnego linku. Utwórz go w zakładce Dostęp.",
      zobaczUwagi: "Zobacz uwagi",
    },
    pakietyMaterialow: {
      tytul: "Materiały",
      opis: "Pakiety miesięczne tego klienta. Nowy pakiet zakładasz w kreatorze na wklejanych linkach do folderów na Dysku.",
      brak: "Ten klient nie ma jeszcze pakietów materiałów.",
      kolumny: { miesiac: "Miesiąc", status: "Status", wyslano: "Wysłano", auto: "Auto-akceptacja", uwagi: "Uwagi" },
      otworz: "Otwórz pakiet",
      wroc: "Wróć do listy pakietów",
      akcje: {
        tytul: "Akcje zespołu",
        wyslij: "Wyślij do akceptacji",
        wycofaj: "Wycofaj do szkicu",
        wyslijV2: "Wyślij wersję {n}",
        cofnij: "Cofnij do poprawek",
        zaplanowano: "Zaplanowano",
        autoCheckbox: "Automatyczna akceptacja po terminie",
        autoOpis: "Domyślnie z karty klienta. Odznacz, gdy ten miesiąc ma czekać na ręczną decyzję.",
        powod: "Powód cofnięcia",
        powodOpis: "Klient zobaczy ten tekst w bursztynowym banerze zamiast zielonego „Zaakceptowano\".",
        powodPodpowiedz: "np. Zła cena w poście 3, poprawiamy grafikę",
        potwierdzCofniecie: "Cofnij do poprawek",
        anuluj: "Anuluj",
        trwa: "Zapisujemy...",
        wycofajPotwierdz: "Wycofać pakiet do szkicu? Klient przestanie go widzieć, licznik zniknie.",
        zaplanowanoPotwierdz: "Oznaczyć jako zaplanowany? Potwierdzasz, że publikacje są ustawione w Meta Business Suite.",
        wyslanoV2Info: "Wysyłka nowej wersji działa też bez zmian w materiałach (klient napisał, że jednak jest dobrze).",
      },
      braki: "Uzupełnij braki przed wysyłką:",
      ostrzezenia: "Ostrzeżenia (nie blokują wysyłki):",
      odpowiedz: "Odpowiedz",
      odpowiedzPodpowiedz: "Odpowiedź zobaczy klient w tym samym miejscu, pod swoją uwagą.",
      wyslijOdpowiedz: "Wyślij odpowiedź",
      zalatwione: "Oznacz jako załatwione",
      zalatwioneOpis: "Załatwione uwagi nie wstrzymują auto-akceptacji.",
      nierozwiazane: "{n} nierozwiązanych uwag klienta w tej rundzie",
      wstrzymana: "Auto-akceptacja wstrzymana",
      wstrzymanaOpis: "Termin minął, ale klient ma nierozwiązane uwagi. Odpowiedz i oznacz je jako załatwione (cron zatwierdzi przy następnym przebiegu) albo cofnij do poprawek.",
      autoTermin: "Termin auto-akceptacji:",
      autoWylaczona: "Auto-akceptacja wyłączona dla tego pakietu.",
      wyslanoV: "Wysłano {data}, wersja {n}.",
      zaakceptowano: "Zaakceptowano {data} ({rodzaj}) przez {osoba}.",
      rodzajAkceptacji: { reczna: "ręcznie", automatyczna: "automatycznie" },
      nikt: "panel",
    },
    /** Narzędzia nad materiałami w panelu zespołu (SPEC rozdz. 12.6). */
    materialy: {
      dodajMaterial: "Dodaj materiał",
      dodajKampanie: "Dodaj kampanię",
      edytuj: "Edytuj",
      podmien: "Podmień",
      pliki: "Pliki",
      usun: "Usuń",
      usunPotwierdz: "Usunąć ten materiał razem z plikami? Tego nie da się cofnąć.",
      usunKampaniePotwierdz: "Usunąć kampanię razem z reklamą i grafikami? Tego nie da się cofnąć.",
      tylkoSzkic: "Usuwanie działa tylko w szkicu. Po wysyłce podmień plik albo cofnij pakiet do szkicu.",
      nowy: {
        tytul: "Nowy materiał",
        opis: "Plik z komputera. Import z Dysku po wklejonym linku dochodzi w kolejnym etapie.",
        typ: "Rodzaj",
        kampania: "Kampania",
        kampaniaOpis: "Reklama trafia do istniejącej kampanii jako kolejna grafika.",
        tytulPola: "Robocza nazwa",
        tytulPodpowiedz: "np. Post 7 - nowa pizza",
        pozycja: "Pozycja",
        pozycjaOpis: "Puste = na końcu listy.",
        plik: "Plik",
        dodaj: "Dodaj",
      },
      podmiana: {
        tytul: "Pliki materiału",
        opis: "Podmiana zachowuje stary plik w historii oraz wszystkie uwagi klienta. Pozycja materiału zostaje.",
        podmienPlik: "Podmień",
        dodajSlajd: "Dodaj slajd",
        dodajGrafike: "Dodaj grafikę",
        usunPlik: "Usuń",
        usunPlikPotwierdz: "Usunąć ten plik z materiału? Zostanie w historii, ale klient go już nie zobaczy.",
        ostatniPlik: "To ostatni plik tego materiału. Najpierw dodaj nowy, potem usuń stary.",
        wybierz: "Wybierz plik",
        wybierzNowy: "Wybierz nowy plik",
        slajd: "Slajd {n}",
        grafika: "Grafika {n}",
        wideo: "Wideo",
      },
      edycja: {
        tytul: "Edycja materiału",
        tytulPola: "Robocza nazwa",
        opis: "Opis posta / tekst relacji",
        opisPodpowiedz: "Tekst, który klient zobaczy w podglądzie tak, jak na Facebooku.",
        publikacja: "Data i godzina publikacji",
        bezDaty: "Bez daty (materiał niezaplanowany)",
        lokale: "Publikujemy na",
        zapisz: "Zapisz",
        anuluj: "Anuluj",
        bezZmian: "Nic się nie zmieniło.",
      },
      reklama: {
        tytul: "Teksty i nagłówki reklamy",
        opis: "Klient przełącza w podglądzie każdą kombinację grafiki, tekstu i nagłówka. Grafiki dodajesz przez „Pliki\".",
        teksty: "Teksty",
        naglowki: "Nagłówki",
        dodajTekst: "Dodaj tekst",
        dodajNaglowek: "Dodaj nagłówek",
        usunWiersz: "Usuń",
        opisPola: "Opis (pod nagłówkiem)",
        cta: "Przycisk",
        link: "Link (wspólny)",
        perLokal: "Wersje per lokal",
        perLokalOpis: "Puste pole = wersja wspólna. Wypełnij tylko to, co różni się w danym lokalu (najczęściej link).",
        linkLokalu: "Link",
        ctaLokalu: "Przycisk",
        opisLokalu: "Opis",
        wspolny: "wspólny",
        zapisz: "Zapisz reklamę",
      },
      kampania: {
        tytulNowa: "Nowa kampania",
        tytulEdycja: "Kampania",
        nazwa: "Nazwa",
        nazwaPodpowiedz: "np. Kampania standardowa, Imprezy okolicznościowe",
        cel: "Cel",
        bezCelu: "Bez celu",
        notatka: "Zdanie dla klienta",
        notatkaPodpowiedz: "Po co ta kampania, np. chcemy dowozić rezerwacje na urodziny i komunie.",
        folder: "Link do folderu z reklamami na Dysku",
        folderOpis: "Grafiki oraz dokument z tekstami i nagłówkami. Osobny folder na każdą kampanię.",
        zapisz: "Zapisz kampanię",
        dodaj: "Dodaj kampanię",
      },
      potwierdzenie: {
        tytul: "Ten materiał jest już zaakceptowany",
        opis: "Klient zaakceptował ten miesiąc. Po zmianie materiał dostanie plakietkę, klient zobaczy baner o podmianie, a zespół dostanie powiadomienie.",
        checkbox: "Rozumiem, zmieniam zaakceptowany materiał",
        wymagane: "Zaznacz, że zmieniasz zaakceptowany materiał.",
      },
      upload: {
        wybierz: "Wybierz plik z komputera",
        formaty: "JPG, PNG, WEBP, HEIC do 25 MB albo MP4, MOV do 300 MB.",
        wysylanie: "Wysyłamy plik... {procent}%",
        sprawdzanie: "Sprawdzamy plik i robimy podglądy...",
        gotowy: "Plik gotowy: {nazwa}",
        duzeWideo: "Wideo waży ponad 150 MB. Wyślij, ale sprawdź, czy da się je odchudzić.",
        bezPodgladu: "Nie udało się zrobić podglądu (format HEIC). Klient zobaczy oryginał, jeśli jego przeglądarka go otworzy.",
        bledy: {
          nieobslugiwany: "Ten format nie jest obsługiwany. Wyślij JPG, PNG, WEBP, HEIC, MP4 albo MOV.",
          zaDuzy: "Plik jest za duży. Limit: {limit}.",
          niezgodnyZDeklaracja: "Zawartość pliku nie zgadza się z jego rozszerzeniem. Sprawdź, co wysyłasz.",
          pozwolenie: "Pozwolenie na wysyłkę wygasło. Wybierz plik jeszcze raz.",
          brakPliku: "Plik nie dotarł do magazynu. Sprawdź połączenie i spróbuj ponownie.",
          przetwarzanie: "Nie udało się przetworzyć obrazu. Spróbuj zapisać go ponownie jako JPG.",
          wysylka: "Wysyłka pliku się nie powiodła. Sprawdź połączenie i spróbuj ponownie.",
        },
      },
      bledy: {
        brak_materialu: "Nie znaleziono materiału. Odśwież stronę.",
        brak_pliku: "Nie znaleziono pliku. Odśwież stronę.",
        zly_typ: "Ta operacja nie dotyczy tego rodzaju materiału.",
        brak_kampanii: "Wybierz kampanię, do której trafi reklama.",
        ostatni_plik: "To ostatni plik tego materiału. Najpierw dodaj nowy, potem usuń stary.",
        tylko_szkic: "To działa tylko w szkicu.",
        istnieje: "Ten klient ma już pakiet na ten miesiąc (i lokal). Otwórz istniejący pakiet.",
        zle_dane: "Sprawdź wypełnione pola.",
        wymaga_potwierdzenia: "Zaznacz, że zmieniasz zaakceptowany materiał.",
        ogolny: "Nie udało się zapisać. Odśwież stronę i spróbuj ponownie.",
      },
      zapisano: "Zapisano.",
      zapisanoPlakietka: { nowe: "Zapisano. Klient zobaczy plakietkę „Nowe\".", poprawione: "Zapisano. Klient zobaczy plakietkę „Poprawione\"." },
      zapisanoTermin: "Termin auto-akceptacji przesunięty na {termin}.",
    },
    /** Kreator pakietu na wklejanych linkach (SPEC rozdz. 12.3). */
    kreator: {
      tytul: "Nowy pakiet materiałów",
      opis: "Pakiet powstaje w szkicu. Wklej linki do folderów na Dysku (osobny folder z contentem, osobny folder z reklamami dla każdej kampanii). Import z Dysku dochodzi w kolejnym etapie; do tego czasu materiały dodajesz przyciskiem „Dodaj materiał\".",
      nowyPakiet: "Nowy pakiet",
      krokKlient: "1. Klient i miesiąc",
      krokContent: "2. Folder z contentem",
      krokKampanie: "3. Kampanie",
      miesiac: "Miesiąc",
      rok: "Rok",
      lokal: "Lokal",
      lokalOpis: "Klient z osobnymi restauracjami ma osobny pakiet na każdy lokal.",
      lokalWspolny: "Jeden pakiet dla wszystkich lokali (kategoria 2 i 3).",
      tytulPakietu: "Tytuł",
      miesiacWspolpracy: "{n}. miesiąc współpracy",
      folderContentu: "Link do folderu z contentem na Dysku",
      folderContentuOpis: "Folder „content {N} mies\" z podfolderami „1. Posty\" i „2. Relacje\". Panel nie zgaduje ścieżek: albo wklejasz link, albo folderu nie ma.",
      linkRozpoznany: "Rozpoznano folder o identyfikatorze {id}.",
      linkNierozpoznany: "To nie wygląda na link do folderu na Dysku Google.",
      importWkrotce: "Karta weryfikacyjna i import z folderu dochodzą w kolejnym etapie. Link zapisujemy już teraz.",
      kampanieOpis: "Kampanii bywa kilka w miesiącu: standardowa, na imprezy okolicznościowe, na polubienia strony. Każda ma własny folder z reklamami.",
      bezKampanii: "Pakiet bez kampanii da się wysłać, ale dostaniesz ostrzeżenie przy wysyłce.",
      usunKampanie: "Usuń kampanię",
      utworz: "Utwórz pakiet",
      tworzenie: "Tworzymy...",
      anuluj: "Anuluj",
      bledy: {
        zlyLink: "To nie jest link do folderu na Dysku Google. Wklej adres z paska przeglądarki.",
        brakLokalu: "Wybierz lokal, którego dotyczy pakiet.",
        brakNazwyKampanii: "Każda kampania musi mieć nazwę.",
      },
    },
    /** Harmonogram zespołu (SPEC rozdz. 8): przeciąganie po kalendarzu i panel „Niezaplanowane". */
    harmonogram: {
      tytul: "Harmonogram",
      opis: "Przeciągnij materiał na dzień publikacji albo ustaw datę w polu obok. Kampanie reklamowe nie mają daty i są poza kalendarzem.",
      poprzedni: "Poprzedni miesiąc",
      nastepny: "Następny miesiąc",
      niezaplanowane: "Niezaplanowane",
      niezaplanowaneOpis: "Materiały bez daty publikacji. Każdy post i każda relacja musi mieć datę przed wysyłką do akceptacji.",
      wszystkoZaplanowane: "Wszystkie materiały mają datę.",
      pozaMiesiacem: "Poza tym miesiącem",
      kampanie: "Kampanie reklamowe w tym miesiącu",
      bezKampanii: "Brak kampanii.",
      brakPakietow: "Ten klient nie ma pakietu na ten miesiąc.",
      pakiet: "Pakiet",
      dzienZakonczenia: "Dzień zakończenia",
      dzienZakonczeniaOpis: "Data zakończenia pakietu z planu contentu (period_to).",
      godzinyDomyslne: "Domyślne godziny publikacji",
      godzinyDomyslneOpis: "Materiał upuszczony na dzień dostaje pierwszą wolną z tych godzin. Wpisz godziny po przecinku, np. 12, 18.",
      godzina: "Godzina",
      data: "Data",
      ustaw: "Ustaw",
      usunDate: "Bez daty",
      upuscTutaj: "Upuść tutaj",
      przeciagnij: "Przeciągnij, żeby zmienić dzień",
      zapisywanie: "Zapisujemy...",
      podglad: "Podgląd",
      typ: { post: "Post", relacja: "Relacja", reels: "Reels", reklama: "Reklama" },
      bledy: { zlaData: "Wpisz poprawną datę.", zleGodziny: "Wpisz od 1 do 6 godzin z zakresu 0-23, po przecinku." },
    },
    /** Skrzynka uwag (SPEC rozdz. 12.5). */
    skrzynka: {
      tytul: "Skrzynka uwag",
      opis: "Nierozwiązane uwagi klientów ze wszystkich pakietów. Odpowiadasz stąd i oznaczasz „Załatwione\".",
      brak: "Nie ma nierozwiązanych uwag. Wszystko załatwione.",
      filtrKlient: "Klient",
      filtrTyp: "Rodzaj",
      wszyscy: "Wszyscy klienci",
      wszystkieTypy: "Wszystkie rodzaje",
      doPakietu: "Cały miesiąc",
      typ: { post: "Post", relacja: "Relacja", reels: "Reels", reklama: "Reklama", pakiet: "Cały miesiąc" },
      otworzPakiet: "Otwórz pakiet",
      odpowiedzi: "{n} odp.",
      poAkceptacji: "po akceptacji",
      nieprzeczytana: "nowa",
      liczba: "{n} do załatwienia",
      filtruj: "Filtruj",
    },
    dostep: {
      tytul: "Dostęp klienta",
      opis: "Każda osoba po stronie klienta dostaje własny link i PIN. Dzięki temu widzisz, kto zaakceptował materiały.",
      utworz: "Utwórz link",
      brakLinkow: "Ten klient nie ma jeszcze żadnego linku. Utwórz pierwszy.",
      kolumny: { osoba: "Osoba", utworzono: "Utworzono", ostatnieWejscie: "Ostatnie wejście", status: "Status", urzadzenia: "Urządzenia" },
      status: { aktywny: "Aktywny", wygaszony: "Wygaszony", zablokowany: "Zablokowany do", tylkoPodglad: "tylko podgląd" },
      nigdy: "jeszcze nie",
      demo: "To klient demonstracyjny do pokazywania panelu. Nie wystawiamy mu linków dostępu ani faktur. Zespół ogląda go przez „Zobacz jak klient\".",
      akcje: {
        pokazLink: "Pokaż link",
        ukryjLink: "Ukryj",
        kopiujLink: "Kopiuj link",
        wygas: "Wygaś link",
        wygasPotwierdz: "Wygasić ten link? Osoba straci dostęp przy następnym wejściu. Tego nie da się cofnąć.",
        wylogujUrzadzenia: "Wyloguj wszystkie urządzenia",
        wylogujPotwierdz: "Wylogować wszystkie urządzenia tego linku? Osoba będzie musiała ponownie wpisać PIN.",
        resetujPin: "Zresetuj PIN",
        resetujPotwierdz: "Zresetować PIN? Stary PIN przestanie działać, a wszystkie urządzenia zostaną wylogowane. Nowy PIN zobaczysz tylko raz.",
      },
      nowy: {
        tytul: "Nowy link dostępu",
        osoba: "Osoba kontaktowa",
        innaOsoba: "Inna osoba (wpisz opis)",
        etykieta: "Opis linku",
        etykietaPodpowiedz: "np. Marek - właściciel",
        rodzajPinu: "Rodzaj PIN-u",
        pin4: "4 cyfry (domyślnie)",
        pin6: "6 cyfr",
        haslo: "Proste hasło",
        mozeAkceptowac: "Ta osoba może akceptować materiały",
        tylkoPodgladOpis: "Bez zaznaczenia: link tylko do podglądu i komentarzy, bez przycisków decyzji.",
        utworz: "Utwórz",
        tworzenie: "Tworzymy...",
        anuluj: "Anuluj",
      },
      gotowy: {
        tytul: "Link i PIN gotowe",
        opis: "PIN widzisz tylko teraz. Skopiuj oba pola i przekaż je klientowi tak, jak zwykle (np. na WhatsAppie). Wiadomość piszesz sam.",
        link: "Link",
        pin: "PIN",
        kopiuj: "Kopiuj",
        skopiowano: "Skopiowano",
        kopiujOba: "Kopiuj link i PIN",
        zamknij: "Zamknij",
        nowyPinTytul: "Nowy PIN",
        nowyPinOpis: "Stary PIN przestał działać, urządzenia zostały wylogowane. Nowy PIN widzisz tylko teraz.",
      },
      historia: {
        tytul: "Historia logowań",
        brak: "Jeszcze nic się nie wydarzyło.",
        kolumny: { kiedy: "Kiedy", co: "Zdarzenie", kto: "Link" },
        zdarzenia: {
          "klient.logowanie_ok": "Udane logowanie",
          "klient.logowanie_blad": "Nieudana próba logowania",
          "klient.blokada_24h": "Blokada linku na 24 godziny (10 nieudanych prób)",
          "klient.wylogowanie": "Wylogowanie",
          "klient.plik_pobrany": "Pobranie pliku",
          "link.utworzony": "Utworzono link",
          "link.wygaszony": "Wygaszono link",
          "link.pin_zresetowany": "Zresetowano PIN",
          "link.urzadzenia_wylogowane": "Wylogowano wszystkie urządzenia",
          "link.skopiowany": "Skopiowano dostęp",
          "link.odszyfrowany": "Pokazano link (odszyfrowano token)",
        },
      },
      bledy: {
        klientDemo: "Klient demonstracyjny nie dostaje linków dostępu.",
        brakEtykiety: "Wpisz opis linku albo wybierz osobę kontaktową.",
        ogolny: "Nie udało się wykonać tej operacji. Odśwież stronę i spróbuj ponownie.",
      },
    },
    faktury: {
      tytul: "Faktury",
      wkrotce: "Faktury dochodzą w kolejnym etapie.",
    },
    ustawienia: {
      tytul: "Ustawienia",
      zespol: {
        tytul: "Zespół",
        opis: "Tylko osoby z tej listy mogą zalogować się do panelu zespołu. Dodanie osoby tworzy jej konto; kod logowania dostaje na e-mail przy pierwszym wejściu.",
        dodaj: "Dodaj osobę",
        imie: "Imię",
        email: "Adres e-mail",
        rola: "Rola",
        dodawanie: "Dodajemy...",
        kolumny: { osoba: "Osoba", email: "E-mail", rola: "Rola", status: "Status" },
        aktywny: "Aktywny",
        nieaktywny: "Nieaktywny",
        dezaktywuj: "Dezaktywuj",
        aktywuj: "Aktywuj",
        bledy: {
          dane: "Uzupełnij imię, poprawny adres e-mail i rolę.",
          istnieje: "Osoba z tym adresem już jest na liście.",
          ogolny: "Nie udało się dodać osoby. Spróbuj ponownie.",
          allowlista: "Ten adres nie przechodzi filtra domen (TEAM_EMAIL_ALLOWLIST). Dopisz domenę albo adres do zmiennej środowiskowej.",
        },
      },
    },
  },
  regulamin: {
    tytul: "Regulamin panelu klienta Foodie Media",
    obowiazujeOd: "Obowiązuje od 3 września 2026",
    sekcje: [
      {
        naglowek: "§ 1. Kto prowadzi panel",
        tresc: [
          {
            punkty: [
              "Panel dostępny pod adresem panel.foodiemedia.pl prowadzi **Foodie Media Sp. z o.o.** z siedzibą w Łodzi, ul. Henryka Sienkiewicza 85/87 lok. 8, 90-057 Łódź, NIP 7252349929, REGON 540281469, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego pod numerem KRS 0001140926, dalej: **Agencja**.",
              "Kontakt w sprawach panelu: kontakt@foodiemedia.pl.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 2. Co znaczą używane pojęcia",
        tresc: [
          {
            punkty: [
              "**Klient** - przedsiębiorca, z którym Agencja zawarła umowę o świadczenie usług marketingowych.",
              "**Panel** - narzędzie internetowe, w którym Klient przegląda i akceptuje materiały, ogląda harmonogram publikacji, raporty, faktury i dokumenty.",
              "**Osoba upoważniona** - osoba wskazana przez Klienta, która otrzymuje dostęp do Panelu i działa w imieniu Klienta.",
              "**Materiały** - posty, relacje, filmy i kreacje reklamowe wraz z tekstami, przygotowane przez Agencję w ramach umowy.",
              "**Pakiet** - zestaw Materiałów przygotowany na dany miesiąc współpracy, obejmujący treści organiczne i kampanie reklamowe.",
              "**Akceptacja** - zgoda Klienta na publikację Materiałów w kształcie przedstawionym w Panelu.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 3. Do czego służy Panel",
        tresc: [
          {
            punkty: [
              "Panel jest narzędziem roboczym w ramach umowy między Agencją a Klientem. Nie jest odrębną usługą i nie podlega odrębnej opłacie.",
              "Panel służy do: przeglądania i akceptacji Materiałów, zgłaszania uwag, podglądu harmonogramu publikacji, dostępu do raportów miesięcznych, faktur i dokumentów oraz zapoznania się z dodatkowymi usługami Agencji.",
              "Panel nie służy do zawierania umów ani do dokonywania płatności.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 4. Dostęp i bezpieczeństwo",
        tresc: [
          {
            punkty: [
              "Dostęp do Panelu odbywa się przez indywidualny link oraz kod PIN lub hasło, przekazywane Osobie upoważnionej przez opiekuna Klienta.",
              "Link wraz z kodem stanowią dane dostępowe. Klient odpowiada za to, komu je przekazuje, i zobowiązuje się nie udostępniać ich osobom nieuprawnionym.",
              "Klient niezwłocznie informuje Agencję o utracie kontroli nad danymi dostępowymi lub o podejrzeniu dostępu osoby nieuprawnionej. Agencja wygasza wtedy dane dostępowe i wydaje nowe.",
              "Klient może w każdej chwili poprosić o dodanie lub odebranie dostępu konkretnej Osobie upoważnionej.",
              "Agencja odnotowuje w systemie datę i godzinę logowań, akceptacji i zgłoszonych uwag. Zapisy te służą ustaleniu przebiegu współpracy.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 5. Akceptacja Materiałów",
        tresc: [
          {
            punkty: [
              "Agencja udostępnia Pakiet w Panelu i informuje o tym Klienta ustalonym kanałem kontaktu.",
              "Klient akceptuje Pakiet w całości albo zgłasza uwagi do poszczególnych Materiałów.",
              "Klient zgłasza uwagi w terminie 72 godzin od udostępnienia Pakietu w Panelu.",
              "Brak zgłoszenia uwag w tym terminie oznacza akceptację Pakietu i uprawnia Agencję do rozpoczęcia publikacji zgodnie z harmonogramem.",
              "Panel informuje o upływającym terminie w sposób widoczny od chwili udostępnienia Pakietu, w tym o pozostałym czasie i o skutku bezczynności.",
              "Zgłoszenie uwag wstrzymuje bieg terminu. Termin biegnie od nowa od chwili udostępnienia poprawionej wersji Pakietu.",
              "Opiekun Klienta może wydłużyć termin lub wyłączyć automatyczną akceptację dla konkretnego Pakietu, na wniosek Klienta złożony przed jego upływem.",
              "Liczba rund poprawek nie jest ograniczona. Agencja może jednak wskazać, że kolejne poprawki wykraczają poza zakres umowy - wtedy ustala z Klientem odrębne warunki.",
              "Po akceptacji Klient nadal może zgłaszać uwagi. Agencja rozpatruje je i informuje, czy i kiedy jest w stanie je uwzględnić, przy czym Materiały już opublikowane nie podlegają wycofaniu.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 6. Harmonogram publikacji",
        tresc: [
          {
            punkty: [
              "Daty publikacji Materiałów Agencja przedstawia w Panelu. Klient widzi je przy każdym Materiale i w widoku kalendarza.",
              "Harmonogram ma charakter planu. Agencja może przesunąć publikację z przyczyn technicznych lub z powodu ograniczeń platform, informując o tym Klienta.",
              "Kampanie reklamowe nie mają wskazanej daty publikacji - Agencja uruchamia je po akceptacji, w ramach uzgodnionego okresu rozliczeniowego.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 7. Raporty, faktury i dokumenty",
        tresc: [
          {
            punkty: [
              "Raport miesięczny Agencja udostępnia w Panelu jako odnośnik do dokumentu pod indywidualnym adresem.",
              "Faktury w Panelu mają charakter informacyjny. Dokumentem księgowym jest faktura wystawiona i doręczona zgodnie z umową.",
              "Statusy płatności w Panelu Agencja aktualizuje na podstawie własnych zapisów. Rozbieżność Klient zgłasza opiekunowi.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 8. Dostępność Panelu",
        tresc: [
          {
            punkty: [
              "Agencja dokłada starań, aby Panel działał bez przerw, ale nie gwarantuje ciągłej dostępności.",
              "Agencja może wprowadzać przerwy techniczne. O przerwach planowanych informuje z wyprzedzeniem.",
              "Niedostępność Panelu nie wstrzymuje biegu terminu z § 5 ust. 3, jeżeli trwała krócej niż 6 godzin. Przy dłuższej niedostępności termin ulega przedłużeniu o czas jej trwania.",
              "Do korzystania z Panelu potrzebne jest urządzenie z dostępem do internetu i aktualna przeglądarka internetowa.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 9. Prawa do Materiałów",
        tresc: [
          {
            punkty: [
              "Zasady przeniesienia praw do Materiałów oraz zakres licencji określa umowa między Agencją a Klientem. Panel nie zmienia tych zasad.",
              "Klient nie udostępnia Materiałów osobom trzecim przed publikacją, poza Osobami upoważnionymi.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 10. Reklamacje",
        tresc: [
          {
            punkty: [
              "Uwagi dotyczące działania Panelu Klient zgłasza na adres kontakt@foodiemedia.pl.",
              "Agencja odpowiada w terminie 14 dni od otrzymania zgłoszenia.",
              "Zgłoszenia dotyczące treści Materiałów Klient kieruje przez Panel albo do opiekuna.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 11. Zmiany regulaminu",
        tresc: [
          {
            punkty: [
              "Agencja może zmienić regulamin z ważnych przyczyn, w szczególności przy zmianie zakresu funkcji Panelu lub przepisów prawa.",
              "O zmianie Agencja informuje Klienta z co najmniej 14-dniowym wyprzedzeniem, przez Panel lub ustalonym kanałem kontaktu.",
              "Zmiana § 5 wymaga odrębnej zgody Klienta i nie wchodzi w życie w trybie z ust. 2.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 12. Postanowienia końcowe",
        tresc: [
          {
            punkty: [
              "W sprawach nieuregulowanych stosuje się umowę między Agencją a Klientem, a w dalszej kolejności przepisy prawa polskiego.",
              "Regulamin stanowi uzupełnienie umowy. W razie sprzeczności pierwszeństwo ma umowa.",
              "Zasady przetwarzania danych osobowych opisuje Polityka prywatności panelu.",
            ],
          },
        ],
      },
    ],
  },
  prywatnosc: {
    tytul: "Polityka prywatności panelu klienta",
    obowiazujeOd: "Obowiązuje od 3 września 2026",
    sekcje: [
      {
        naglowek: "1. Kto odpowiada za Twoje dane",
        tresc: [
          "Administratorem danych osobowych jest **Foodie Media Sp. z o.o.** z siedzibą w Łodzi, ul. Henryka Sienkiewicza 85/87 lok. 8, 90-057 Łódź, NIP 7252349929, REGON 540281469, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego pod numerem KRS 0001140926.",
          "W sprawach dotyczących danych osobowych napisz na kontakt@foodiemedia.pl.",
          "Nie wyznaczyliśmy inspektora ochrony danych - wszystkie sprawy prowadzimy pod tym adresem.",
        ],
      },
      {
        naglowek: "2. Jakie dane przetwarzamy",
        tresc: [
          { podtytul: "Dane osób, które korzystają z panelu:" },
          { lista: ["imię i nazwisko,", "rola w firmie (np. właściciel, manager),", "numer telefonu,", "adres e-mail, jeśli został podany."] },
          { podtytul: "Dane, które powstają w trakcie korzystania z panelu:" },
          {
            lista: [
              "data i godzina logowania oraz nieudanych prób logowania,",
              "data i godzina otwarcia materiałów, akceptacji i zgłoszonych uwag,",
              "treść uwag zgłoszonych w panelu,",
              "skrócony, nieodwracalnie przekształcony zapis adresu IP i informacji o przeglądarce.",
            ],
          },
          "**Czego nie zbieramy:** nie zbieramy w panelu danych gości restauracji, nie prowadzimy analityki zewnętrznej, nie stosujemy cookies marketingowych ani śledzących.",
        ],
      },
      {
        naglowek: "3. Po co i na jakiej podstawie",
        tresc: [
          {
            tabela: {
              naglowki: ["Cel", "Podstawa prawna"],
              wiersze: [
                ["Udostępnienie panelu i realizacja umowy o usługi marketingowe", "art. 6 ust. 1 lit. b RODO - niezbędność do wykonania umowy; wobec osób działających w imieniu klienta: art. 6 ust. 1 lit. f - nasz uzasadniony interes w kontakcie z klientem"],
                ["Ustalenie, kto i kiedy zaakceptował materiały", "art. 6 ust. 1 lit. f - uzasadniony interes: udokumentowanie przebiegu współpracy"],
                ["Zabezpieczenie panelu przed nieuprawnionym dostępem (logi, ograniczanie prób logowania)", "art. 6 ust. 1 lit. f - uzasadniony interes: bezpieczeństwo danych"],
                ["Wystawianie i przechowywanie faktur", "art. 6 ust. 1 lit. c - obowiązek prawny wynikający z przepisów podatkowych i o rachunkowości"],
                ["Rozpatrywanie reklamacji i obrona przed roszczeniami", "art. 6 ust. 1 lit. f - uzasadniony interes"],
              ],
            },
          },
        ],
      },
      {
        naglowek: "4. Komu powierzamy dane",
        tresc: [
          "Korzystamy z dostawców, którzy przetwarzają dane na nasze zlecenie:",
          {
            lista: [
              "**Supabase** - baza danych i przechowywanie plików; serwery w regionie Europy (Frankfurt, Niemcy),",
              "**Vercel** - hosting aplikacji; funkcje uruchamiane w regionie Frankfurt,",
              "**Resend** - wysyłka wiadomości z kodami logowania,",
              "**Google** - przechowywanie plików źródłowych materiałów na Dysku Google,",
              "**Zapier** - przekazywanie powiadomień o zdarzeniach w panelu do naszego komunikatora wewnętrznego,",
              "**Slack** - komunikacja wewnętrzna zespołu obsługującego klienta.",
            ],
          },
          "Supabase, Vercel i Resend są spółkami z siedzibą w Stanach Zjednoczonych, mimo że dane przechowujemy w Unii Europejskiej. Przekazanie danych poza Europejski Obszar Gospodarczy może więc wystąpić w zakresie obsługi technicznej. Odbywa się ono na podstawie standardowych klauzul umownych zatwierdzonych przez Komisję Europejską.",
          "Danych nie sprzedajemy i nie udostępniamy do celów marketingowych podmiotom trzecim.",
        ],
      },
      {
        naglowek: "5. Jak długo trzymamy dane",
        tresc: [
          {
            tabela: {
              naglowki: ["Rodzaj danych", "Okres"],
              wiersze: [
                ["Materiały i historia akceptacji", "24 miesiące od udostępnienia"],
                ["Zapisy logowań i działań w panelu", "12 miesięcy"],
                ["Dane sesji zalogowanych urządzeń", "30 dni od wygaśnięcia sesji, nie dłużej niż 90 dni"],
                ["Dane kontaktowe osób upoważnionych", "czas trwania umowy, a po jej zakończeniu do upływu terminu przedawnienia roszczeń"],
                ["Faktury i dokumenty księgowe", "okres wymagany przepisami podatkowymi"],
              ],
            },
          },
          "Po zakończeniu współpracy wygaszamy wszystkie dane dostępowe do panelu. Na wniosek Klienta usuwamy materiały wcześniej.",
        ],
      },
      {
        naglowek: "6. Twoje prawa",
        tresc: [
          "Masz prawo do:",
          {
            lista: [
              "dostępu do swoich danych i otrzymania ich kopii,",
              "sprostowania danych nieprawidłowych lub niekompletnych,",
              "usunięcia danych,",
              "ograniczenia przetwarzania,",
              "przenoszenia danych,",
              "sprzeciwu wobec przetwarzania opartego na naszym uzasadnionym interesie.",
            ],
          },
          "Żeby skorzystać z któregokolwiek, napisz na kontakt@foodiemedia.pl. Odpowiadamy w ciągu miesiąca.",
          "Masz też prawo wnieść skargę do **Prezesa Urzędu Ochrony Danych Osobowych**, ul. Stawki 2, 00-193 Warszawa.",
        ],
      },
      {
        naglowek: "7. Czy podanie danych jest obowiązkowe",
        tresc: ["Podanie imienia, nazwiska i numeru telefonu jest dobrowolne, ale bez nich nie jesteśmy w stanie wydać dostępu do panelu ani przekazać danych logowania."],
      },
      {
        naglowek: "8. Automatyczne decyzje i profilowanie",
        tresc: [
          "Nie profilujemy Cię i nie podejmujemy wobec Ciebie decyzji wyłącznie w sposób zautomatyzowany na podstawie analizy Twoich danych.",
          "Panel zawiera mechanizm automatycznej akceptacji materiałów po upływie 72 godzin, opisany w regulaminie. Jest to uzgodniony umownie sposób liczenia terminu, a nie decyzja podejmowana na podstawie analizy danych osobowych.",
        ],
      },
      {
        naglowek: "9. Pliki cookies",
        tresc: [
          "Używamy wyłącznie plików niezbędnych do działania panelu: pliku utrzymującego zalogowanie oraz plików związanych z bezpieczeństwem sesji. Nie stosujemy cookies analitycznych ani marketingowych, dlatego nie prosimy o zgodę na ich użycie.",
        ],
      },
      {
        naglowek: "10. Zmiany polityki",
        tresc: [
          "Politykę możemy zmienić, gdy zmienią się funkcje panelu, dostawcy lub przepisy. O zmianie poinformujemy w panelu z co najmniej 14-dniowym wyprzedzeniem. Data u góry dokumentu zawsze wskazuje aktualną wersję.",
        ],
      },
    ],
  },
  bledy: {
    ogolny: "Coś poszło nie tak. Odśwież stronę, a jeśli to nie pomoże, napisz do swojego opiekuna.",
  },
} as const;

export type Copy = typeof copy;
