/**
 * WSZYSTKIE teksty interfejsu. Zero polskich stringów w JSX (CLAUDE.md, zasada 7).
 * Bez pauz i półpauz: wyłącznie zwykły myślnik. Pilnuje tego tests/unit/copy.test.ts.
 * Do klienta mówimy na Ty, bez żargonu, komunikaty błędów mówią, co zrobić.
 */
export const copy = {
  marka: {
    nazwa: "Foodie Media",
    panel: "Panel klienta Foodie Media",
    opisOg: "Panel klienta Foodie Media",
    panelZespolu: "Panel zespołu Foodie Media",
  },
  start: {
    tytul: "Panel klienta Foodie Media",
    opis: "Tu akceptujesz materiały na kolejny miesiąc, sprawdzasz harmonogram publikacji, raporty i faktury.",
    jakWejsc: "Wejdź z linku, który dostałeś od swojego opiekuna. Link i PIN są tylko dla Ciebie.",
    pomoc: "Nie masz linku albo nie działa? Napisz do swojego opiekuna w Foodie Media.",
    zespol: "Jesteś z zespołu Foodie Media?",
    zespolLink: "Zaloguj się do panelu zespołu",
  },
  pin: {
    tytul: "Wpisz PIN",
    opis: "Wpisz swój PIN. Jeśli wchodzisz pierwszy raz, wpisz kod startowy od swojego opiekuna w Foodie Media.",
    etykieta: "PIN albo kod startowy",
    zapamietaj: "Zapamiętaj mnie na tym urządzeniu",
    przycisk: "Wejdź do panelu",
    trwa: "Sprawdzamy...",
    blad: "Nie udało się wejść. Sprawdź, czy otwierasz właściwy link i wpisujesz właściwy PIN. Jeśli to się powtarza, napisz do swojego opiekuna.",
    limit: "Za dużo prób w krótkim czasie. Odczekaj chwilę i spróbuj ponownie.",
    kodWygasl: "Ten kod startowy już wygasł. Napisz do swojego opiekuna, dostaniesz nowy.",
  },
  /** Pierwsze wejście z kodem startowym (Etap 2 planu domknięcia): klient ustawia własny PIN. */
  ustawPin: {
    tytul: "Ustaw swój PIN",
    opis: "To będzie Twój PIN do panelu. Przy następnych wejściach wpisujesz go zamiast kodu od opiekuna.",
    nowy: "Nowy PIN (4 do 6 cyfr)",
    powtorz: "Powtórz PIN",
    wskazowka: "Nie używaj PIN-u do karty ani do telefonu. Unikaj dat, lat i prostych ciągów, np. 1234.",
    przycisk: "Zapisz PIN i wejdź",
    trwa: "Zapisujemy...",
    bledy: {
      format: "PIN to od 4 do 6 cyfr.",
      slaby: "Ten PIN łatwo zgadnąć. Wybierz inny, bez dat, lat, powtórzeń i ciągów.",
      rozne: "PIN-y się różnią. Wpisz ten sam PIN dwa razy.",
      jakKod: "Wybierz inny PIN niż kod startowy od opiekuna.",
      limit: "Za dużo prób w krótkim czasie. Odczekaj chwilę i spróbuj ponownie.",
    },
  },
  /** „Zmień PIN" w panelu klienta: obecny PIN, nowy, powtórzenie. */
  zmianaPinu: {
    tytul: "Zmień PIN",
    opis: "Po zmianie PIN-u wylogujemy wszystkie inne urządzenia, na których korzystasz z tego linku.",
    obecny: "Obecny PIN",
    przycisk: "Zmień PIN",
    trwa: "Zmieniamy...",
    bledy: {
      obecny: "To nie jest Twój obecny PIN. Sprawdź i spróbuj ponownie.",
      takiSam: "Nowy PIN musi być inny niż obecny.",
      zablokowany: "Za dużo nieudanych prób. Spróbuj później albo napisz do swojego opiekuna.",
      ogolny: "Nie udało się zmienić PIN-u. Zaloguj się ponownie i spróbuj jeszcze raz.",
    },
  },
  nawigacja: {
    start: "Start",
    materialy: "Materiały do akceptacji",
    harmonogram: "Harmonogram",
    archiwum: "Archiwum materiałów",
    raporty: "Raporty",
    faktury: "Faktury i dokumenty",
    pakiet: "Twój pakiet",
    uslugi: "Co jeszcze możemy zrobić",
    wdrozenie: "Wdrożenie",
    wkrotce: "wkrótce",
    wyloguj: "Wyloguj",
    zmienPin: "Zmień PIN",
    zalogowanyJako: "Zalogowano jako",
    wiecej: "Więcej",
    wiecejTytul: "Pozostałe sekcje",
  },
  klientStart: {
    powitanie: "Cześć",
    pinUstawiony: "Gotowe, Twój PIN jest ustawiony. Przy następnym wejściu wpisz go zamiast kodu od opiekuna.",
    pinZmieniony: "PIN zmieniony. Na innych urządzeniach zaloguj się nowym PIN-em.",
    doAkceptacji: "Czeka na Twoją akceptację",
    przejrzyj: "Przejrzyj materiały",
    autoAkceptacja: "Automatyczna akceptacja",
    autoWylaczona: "Bez automatycznej akceptacji",
    wersja: "wersja",
    naBiezaco: "Wszystko na bieżąco",
    naBiezacoOpis: "Nie ma materiałów do akceptacji. Gdy przygotujemy kolejny miesiąc, zobaczysz to tutaj i dostaniesz wiadomość od opiekuna.",
    posty: { jeden: "post", kilka: "posty", wiele: "postów" },
    relacje: { jeden: "relacja", kilka: "relacje", wiele: "relacji" },
    kampanie: { jeden: "kampania reklamowa", kilka: "kampanie reklamowe", wiele: "kampanii reklamowych" },
    /** Kafle pod głównym (SPEC rozdz. 5.1): najnowszy raport, najbliższa publikacja, faktura po terminie. */
    kafle: {
      raport: "Najnowszy raport",
      raportOtworz: "Otwórz raport",
      raportBrak: "Pierwszy raport pojawi się po zakończeniu miesiąca współpracy.",
      publikacja: "Najbliższa publikacja",
      publikacjaBrak: "Nie ma jeszcze zaplanowanych publikacji.",
      publikacjaLink: "Zobacz harmonogram",
      fakturaTytul: "Faktura po terminie",
      fakturaOpis: "Faktura {numer} miała termin płatności {termin} ({dni}). Jeśli już ją opłaciłeś, daj znać opiekunowi.",
      fakturaLink: "Zobacz faktury",
    },
  },
  /** Raporty (SPEC rozdz. 5.5, 9): panel tylko linkuje do systemu raportów, bez osadzania. */
  raporty: {
    tytul: "Raporty",
    opis: "Podsumowanie każdego miesiąca współpracy: zasięgi, wyniki reklam, opinie. Raport otwiera się w nowej karcie.",
    brak: "Pierwszy raport pojawi się po zakończeniu pierwszego miesiąca współpracy.",
    otworz: "Otwórz raport",
    miesiacWspolpracy: "{n}. miesiąc współpracy",
    opublikowano: "Opublikowano {data}",
    domyslnyTytul: "Raport miesięczny - {miesiac} {rok}",
  },
  /** Faktury i dokumenty (SPEC rozdz. 5.6, 10). */
  faktury: {
    tytul: "Faktury i dokumenty",
    opis: "Faktury za współpracę i dokumenty, które podpisaliśmy. PDF pobierzesz jednym kliknięciem.",
    brak: "Nie ma jeszcze faktur.",
    kolumny: { numer: "Numer", wystawiono: "Wystawiono", termin: "Termin płatności", netto: "Netto", brutto: "Brutto", status: "Status", pdf: "PDF" },
    status: { do_zaplaty: "Do zapłaty", po_terminie: "Po terminie", oplacona: "Opłacona" },
    poTerminieDni: { jeden: "dzień po terminie", kilka: "dni po terminie", wiele: "dni po terminie" },
    oplaconaDnia: "opłacona {data}",
    pobierz: "Pobierz PDF",
    bezPdf: "PDF w przygotowaniu",
    dokumenty: {
      tytul: "Dokumenty",
      opis: "Umowa, aneksy i umowa powierzenia przetwarzania danych.",
      brak: "Nie ma jeszcze dokumentów.",
      obowiazujeOd: "obowiązuje od {data}",
      pobierz: "Pobierz PDF",
    },
    rodzaje: { umowa: "Umowa", aneks: "Aneks", powierzenie: "Umowa powierzenia przetwarzania danych", inne: "Inny dokument" },
  },
  /** „Twój pakiet" (SPEC rozdz. 5.7): nazwa pakietu, kwota, zakres, lokale, opiekun, start współpracy. Bez logo klienta. */
  twojPakiet: {
    tytul: "Twój pakiet",
    opis: "Co obejmuje współpraca i kto się Tobą opiekuje.",
    miesiecznie: "netto miesięcznie",
    kwotaWUmowie: "Kwotę znajdziesz w umowie.",
    zakres: "Co obejmuje pakiet",
    zakresPakietow: {
      foodie_one: ["6 postów w miesiącu, w tym Reels", "10 relacji w miesiącu", "Co najmniej jedna kampania reklamowa w miesiącu", "Harmonogram publikacji i akceptacja materiałów w panelu", "Raport miesięczny z wynikami"],
      foodie_360: ["6 postów w miesiącu, w tym Reels", "10 relacji w miesiącu", "Co najmniej jedna kampania reklamowa w miesiącu", "Dodatkowe działania ustalone w umowie", "Harmonogram publikacji i akceptacja materiałów w panelu", "Raport miesięczny z wynikami"],
      siec: ["6 postów w miesiącu, w tym Reels, wspólnych dla całej sieci", "10 relacji w miesiącu", "Kampanie reklamowe z osobną wersją dla każdego lokalu", "Harmonogram publikacji i akceptacja materiałów w panelu", "Raport miesięczny z wynikami"],
    },
    zakresUwaga: "Szczegółowy zakres współpracy jest w umowie, w zakładce Faktury i dokumenty.",
    lokale: "Lokale objęte współpracą",
    lokaleOpis: { jeden: "lokal", kilka: "lokale", wiele: "lokali" },
    opiekun: "Twój opiekun",
    opiekunBrak: "Opiekun zostanie przypisany wkrótce. Do tego czasu pisz na adres poniżej.",
    kontaktAgencji: "kontakt@foodiemedia.pl",
    kontaktOpis: "Najszybciej odpowiadamy na WhatsAppie i e-mailu.",
    wspolpracaOd: "Współpracujemy od",
    raportyLink: "Zobacz raporty",
  },
  /** „Co jeszcze możemy zrobić" (SPEC rozdz. 5.8): karty usług i jedno pole. */
  uslugi: {
    tytul: "Co jeszcze możemy zrobić",
    opis: "Usługi, które łączymy z prowadzeniem Twoich profili. Kliknij, a odezwiemy się z konkretami.",
    brak: "Nie mamy teraz dodatkowych usług dla Twojego pakietu.",
    cta: "Chcę wiedzieć więcej",
    juzZgloszone: "Zgłoszone {data}",
    dialog: {
      pole: "Napisz w dwóch zdaniach, co Cię interesuje",
      podpowiedz: "np. Chciałbym sesję zdjęciową nowego menu w październiku.",
      wyslij: "Wyślij",
      wysylanie: "Wysyłamy...",
      anuluj: "Anuluj",
      licznik: "{n} / 1000",
      podglad: "W podglądzie nie da się wysłać zgłoszenia.",
    },
    potwierdzenie: {
      tytul: "Dziękujemy!",
      opis: "Odezwiemy się w ciągu jednego dnia roboczego.",
      zamknij: "Zamknij",
    },
    bledy: {
      pusty: "Napisz choć jedno zdanie, żebyśmy wiedzieli, od czego zacząć.",
      zaDlugi: "Wiadomość może mieć najwyżej 1000 znaków.",
      brakUslugi: "Tej usługi już nie ma w ofercie. Odśwież stronę.",
      ogolny: "Nie udało się wysłać zgłoszenia. Spróbuj ponownie albo napisz do opiekuna.",
    },
  },
  /** Wdrożenie (SPEC rozdz. 11): trasa istnieje za flagą, kroki tylko do odczytu. */
  wdrozenie: {
    tytul: "Wdrożenie",
    opis: "Kroki, które przechodzimy razem na starcie współpracy.",
    postep: "{zrobione} z {wszystkie} kroków",
    brakKrokow: "Twój opiekun przygotowuje kroki wdrożenia.",
    zrobione: "Zrobione {data}",
    doZrobienia: "Do zrobienia",
    formularz: "Otwórz formularz",
    instrukcja: "Otwórz instrukcję",
  },
  materialy: {
    wBudowie: "Ekran akceptacji materiałów powstaje w kolejnym etapie. Na razie zobaczysz tu podsumowanie pakietu.",
    wroc: "Wróć na start",
    status: {
      szkic: "Szkic",
      do_akceptacji: "Do akceptacji",
      poprawki: "Poprawki",
      zaakceptowany: "Zaakceptowany",
      zaplanowany: "Zaplanowany",
    },
  },
  /** Podsumowania zdarzeń do Zapiera (SPEC rozdz. 15). Zmienne: {klient}, {okres}, {osoba}, {wersja}, {uwagi}, {powod}. */
  zdarzenia: {
    system: "panel (automatycznie)",
    podsumowanie: {
      "pakiet.wyslany": "Materiały {klient} na {okres} wysłane do akceptacji (wersja {wersja}) przez {osoba}.",
      "pakiet.otwarty": "{osoba} ({klient}) otworzył(a) materiały na {okres} pierwszy raz.",
      "pakiet.zaakceptowany": "{osoba} ({klient}) zaakceptował(a) materiały na {okres}.",
      "pakiet.zaakceptowany_auto": "Materiały {klient} na {okres} zostały zaakceptowane automatycznie po upływie terminu.",
      "pakiet.poprawki": "{osoba} ({klient}) zgłosił(a) uwagi do materiałów na {okres}. Liczba uwag: {uwagi}.",
      "pakiet.nieotwarty_po_24h": "{klient} nie otworzył(a) materiałów na {okres} przez 24 godziny od wysyłki.",
      "pakiet.auto_za_24h": "Do automatycznej akceptacji materiałów {klient} na {okres} zostały 24 godziny.",
      "pakiet.auto_wstrzymana_uwagi": "Termin auto-akceptacji materiałów {klient} na {okres} minął, ale klient ma nierozwiązane uwagi ({uwagi}). Odpowiedz na nie i oznacz jako załatwione.",
      "pakiet.wycofany": "Materiały {klient} na {okres} wycofane do szkicu przez {osoba}.",
      "pakiet.cofniety_do_poprawek": "Zaakceptowane materiały {klient} na {okres} cofnięte do poprawek przez {osoba}. Powód: {powod}",
      "komentarz.po_akceptacji": "{osoba} ({klient}) dodał(a) uwagę po akceptacji materiałów na {okres}.",
      "material.podmieniony_po_akceptacji": "W zaakceptowanych materiałach {klient} na {okres} podmieniono materiał ({osoba}).",
    },
    /** Zainteresowanie usługą (rozdz. 5.8): bez okresu pakietu. Zmienne: {osoba}, {klient}, {usluga}. */
    zainteresowanie: "{osoba} ({klient}) chce wiedzieć więcej o usłudze: {usluga}.",
    /** Retencja (rozdz. 17): zgłoszenie do admina, bez okresu. Zmienne: {n}. */
    retencja: "Retencja: {n} pakietów czeka na decyzję admina (Ustawienia, Retencja).",
    /** Dostęp klienta (Etap 2 planu domknięcia): blokady, zamrożenie, własny PIN. Zmienne: {osoba}, {klient}. */
    dostep: {
      "bezpieczenstwo.blokada": "Link {osoba} ({klient}) zablokowany na 24 godziny po 10 nieudanych próbach PIN-u.",
      "bezpieczenstwo.link_zamrozony": "Link {osoba} ({klient}) zamrożony po drugiej blokadzie w ciągu 30 dni. Jeśli to był klient, wydaj mu nowy kod startowy w zakładce Dostęp.",
      "klient.pin_ustawiony": "{osoba} ({klient}) ustawił(a) własny PIN do panelu.",
      "klient.pin_zmieniony": "{osoba} ({klient}) zmienił(a) PIN do panelu. Jeśli to nie był klient, wydaj nowy kod startowy w zakładce Dostęp.",
    },
  },
  /** Walidacja przed wysyłką do akceptacji (SPEC rozdz. 8): braki blokują, ostrzeżenia nie. */
  wysylka: {
    brakDaty: "{tytul}: brak daty publikacji",
    bezMaterialow: "Pakiet nie ma żadnych materiałów.",
    bezKampanii: "Pakiet nie ma żadnej kampanii reklamowej. Wysyłka jest możliwa, ale sprawdź, czy to zamierzone.",
    typ: { post: "Post", relacja: "Relacja", reels: "Reels", reklama: "Reklama" },
  },
  /** Odmowy maszyny stanów (SPEC rozdz. 6.8), pokazywane osobie, która kliknęła. */
  przejscia: {
    odmowa: {
      niedozwolone_ze_statusu: "Ta zmiana nie jest możliwa w obecnym statusie pakietu. Odśwież stronę.",
      niewlasciwy_aktor: "Nie masz uprawnień do tej zmiany.",
      link_tylko_do_podgladu: "Twój link pozwala oglądać i komentować materiały. Akceptację zostaw osobie z pełnym dostępem.",
      brak_uwag: "Napisz najpierw, co poprawić - kliknij komentarz przy materiale.",
      brak_powodu: "Wpisz powód cofnięcia. Klient zobaczy go w panelu.",
      auto_wylaczona: "Ten pakiet ma wyłączoną automatyczną akceptację.",
      termin_nie_minal: "Termin automatycznej akceptacji jeszcze nie minął.",
      nierozwiazane_uwagi: "Klient ma nierozwiązane uwagi. Odpowiedz na nie i oznacz jako załatwione albo cofnij pakiet do poprawek.",
      braki_w_materialach: "Uzupełnij braki przed wysyłką.",
      nie_znaleziono: "Nie znaleziono pakietu. Odśwież stronę.",
      konflikt: "Ktoś w międzyczasie zmienił status pakietu. Odśwież stronę i sprawdź, co się zmieniło.",
      klient_nieaktywny: "Współpraca z tym klientem jest wstrzymana albo zakończona. Wznów ją w zakładce Ustawienia karty klienta, zanim wyślesz materiały.",
    },
  },
  /** Ramki podglądów 1:1 (SPEC rozdz. 7). Neutralne teksty interfejsu Facebooka i Instagramu, bez logotypów Meta. */
  podglad: {
    facebook: "Facebook",
    instagram: "Instagram",
    sponsorowane: "Sponsorowane",
    publiczne: "Publiczne",
    zobaczWiecej: "Zobacz więcej",
    lubieTo: "Lubię to!",
    komentarz: "Komentarz",
    udostepnij: "Udostępnij",
    reakcje: "Ty i 41 innych osób",
    komentarze: "3 komentarze",
    udostepnienia: "2 udostępnienia",
    odpowiedz: "Odpowiedz...",
    godzinTemu: "2 godz.",
    obserwuj: "Obserwuj",
    oryginalnyDzwiek: "Oryginalny dźwięk",
    przesunWGore: "Przesuń w górę",
    reels: "Reels",
    wideoWyciszone: "Wideo jest domyślnie wyciszone. Dźwięk włączysz kontrolką odtwarzacza.",
    publikacja: "Publikacja:",
    bezDaty: "bez daty publikacji",
    strona: "Strona",
    slajd: "Slajd {n} z {liczba}",
    poprzedni: "Poprzedni",
    nastepny: "Następny",
    relacja: "Relacja {n} z {liczba}",
    gdzieZobaczysz: "Gdzie zobaczysz reklamę",
    miejsca: {
      fb_kanal_telefon: "Kanał na telefonie",
      fb_kanal_komputer: "Kanał na komputerze",
      fb_relacje: "Relacje",
      fb_reels: "Reels",
      ig_kanal: "Kanał",
      ig_relacje_reels: "Relacje i Reels",
    },
    brakIg: {
      klient: "Podgląd na Instagramie pojawi się, gdy Twój opiekun uzupełni nick na Instagramie.",
      zespol: "Uzupełnij nick na Instagramie w zakładce „Dane i współpraca\" karty klienta, żeby zobaczyć podgląd na Instagramie.",
    },
    warianty: {
      grafika: "Grafika",
      tekst: "Tekst",
      naglowek: "Nagłówek",
      lokal: "Lokal",
      z: "z",
      wszystkieLokale: "Wszystkie lokale (wersja wspólna)",
      kombinacje: "Możesz obejrzeć każdą z {n} kombinacji.",
    },
    elementy: { grafika: "grafika", tekst: "tekst", naglowek: "nagłówek", opis: "opis", cta: "przycisk", link: "link" },
    zrodla: {
      wszystkoWspolne: "Wszystkie elementy tej reklamy są wspólne dla wszystkich lokali.",
      wersjaDlaLokalu: "Wersja dla {lokal}: {elementy}.",
      wspolne: "Wspólne dla wszystkich lokali: {elementy}.",
    },
    wszystkieWarianty: "Zobacz wszystkie warianty",
    ukryjWarianty: "Ukryj wszystkie warianty",
    wszystkieLokalePodpis: "wszystkie lokale",
    grafiki: "Grafiki",
    teksty: "Teksty",
    naglowki: "Nagłówki",
    pozostale: "Opis, przycisk i link",
    ctaDomyslne: "Więcej informacji",
    /** Zamknięta lista przycisków reklamy (SPEC rozdz. 7.4, plan W2): podgląd pokazuje dokładnie ten przycisk, który pokaże Facebook. */
    cta: ["Więcej informacji", "Zarezerwuj", "Zamów teraz", "Wyślij wiadomość", "Polub stronę", "Kup teraz", "Zarejestruj się", "Skontaktuj się", "Zadzwoń", "Pobierz"],
    domenaZastepcza: "twojastrona.pl",
    cele: { sprzedaz: "Sprzedaż", ruch: "Ruch na stronie", polubienia: "Polubienia strony", leady: "Zapytania i rezerwacje", zasieg: "Zasięg", inne: "Inne" },
  },
  /** Ekran pakietu (SPEC rozdz. 6): ten sam dla klienta i podglądu zespołu. */
  pakiet: {
    wersja: "wersja",
    zakladki: { posty: "Posty", relacje: "Relacje", kampanie: "Kampanie", wszystko: "Wszystko" },
    noweOdpowiedzi: "{n} nowe odpowiedzi zespołu",
    obejrzano: "Obejrzano {x} z {y}",
    autoAkceptacja: "Automatyczna akceptacja",
    autoOstatniaDoba: "Zostało 24 godziny",
    autoMinela: "Termin automatycznej akceptacji minął. Czekamy na decyzję zespołu.",
    autoWylaczona: "Bez automatycznej akceptacji",
    licznikZatrzymany: "Licznik automatycznej akceptacji zatrzymany",
    tylkoPodglad: "Twój link pozwala oglądać i komentować materiały. Decyzję podejmie osoba z pełnym dostępem.",
    decyzje: { uwagi: "Zgłaszam uwagi", akceptuj: "Akceptuję wszystko" },
    modalAkceptacji: {
      tytul: "Akceptujesz cały pakiet",
      opis: "Akceptujesz {posty}, {relacje} i {kampanie}. Zaplanujemy publikację zgodnie z harmonogramem.",
      sprawdzilem: "Sprawdziłem daty publikacji",
      zaznaczDaty: "Zaznacz, że sprawdziłeś daty publikacji.",
      ostrzezenieUwagi: "Masz {n} nierozwiązane uwagi. Akceptacja oznacza, że mimo nich ruszamy z publikacją.",
      potwierdz: "Tak, akceptuję",
      anuluj: "Wróć do materiałów",
      trwa: "Zapisujemy...",
    },
    modalUwag: {
      tytul: "Zgłaszasz uwagi",
      opis: "Przekażemy zespołowi Twoje uwagi ({n}). Licznik automatycznej akceptacji się zatrzyma, a materiały wrócą do Ciebie w poprawionej wersji.",
      potwierdz: "Wyślij uwagi",
      anuluj: "Wróć",
      trwa: "Wysyłamy...",
    },
    banery: {
      zaakceptowano: "Zaakceptowano {data} przez {osoba}.",
      zaakceptowanoAuto: "Materiały zostały zatwierdzone automatycznie {data}, zgodnie z zasadami panelu. Nadal możesz dodać uwagi - sprawdzimy je przed publikacją.",
      komentowanieWlaczone: "Nadal możesz dodać uwagi do każdego materiału.",
      poprawki: "Przekazaliśmy uwagi zespołowi. Odezwiemy się z poprawioną wersją.",
      cofniecie: "Cofnęliśmy akceptację {data}: {powod}. Sprawdź poprawione materiały.",
      podmiana: "Po akceptacji podmieniliśmy materiały. Są oznaczone plakietką.",
      zaplanowano: "Publikacje są zaplanowane zgodnie z harmonogramem.",
      szkic: "Ten pakiet jest jeszcze w przygotowaniu.",
    },
    plakietki: { poprawione: "Poprawione", nowe: "Nowe", reels: "Reels", uwagaPoAkceptacji: "Uwaga po akceptacji", zalatwione: "Załatwione", nieprzeczytane: "Nowa odpowiedź", nieprzeczytanaUwaga: "Nowa uwaga" },
    komentarze: {
      tytul: "Uwagi i odpowiedzi",
      brak: "Nie ma jeszcze uwag do tego materiału.",
      dodaj: "Dodaj uwagę",
      doPakietu: "Uwaga do całego pakietu",
      doPakietuOpis: "Coś, co dotyczy wszystkich materiałów, nie jednego posta.",
      podpowiedz: "Napisz, co poprawić. Konkretnie: który element i jak ma wyglądać.",
      wyslij: "Wyślij uwagę",
      wysylanie: "Wysyłamy...",
      anuluj: "Anuluj",
      licznik: "{n} / 4000",
      historia: "Historia uwag (runda {n})",
      odpowiedzZespolu: "Odpowiedź zespołu",
      doCzego: "Do czego",
      calaReklama: "Cała reklama",
      taGrafika: "Ta grafika",
      tenTekst: "Ten tekst",
      tenNaglowek: "Ten nagłówek",
      dotyczy: "Dotyczy: {co}",
      blad: "Nie udało się zapisać uwagi. Spróbuj ponownie.",
      pusty: "Wpisz treść uwagi.",
      zaDlugi: "Uwaga może mieć najwyżej 4000 znaków.",
    },
    kampania: { cel: "Cel:", ktora: "Kampania {n} z {liczba}" },
    lista: {
      tytul: "Materiały do akceptacji",
      opis: "Materiały na kolejne miesiące i to, co już zaakceptowałeś.",
      brak: "Nie ma teraz materiałów do akceptacji.",
      otworz: "Otwórz",
    },
    zespolWidziKlienta: "Tak widzi ten ekran klient. Przyciski decyzji są u klienta, tu masz akcje zespołu poniżej.",
  },
  /** Harmonogram klienta (SPEC rozdz. 5.3, 8): ten sam kalendarz, tylko do odczytu, z komentarzem przy materiale. */
  harmonogram: {
    tytul: "Harmonogram",
    opis: "Daty publikacji postów i relacji. Kampanie reklamowe nie mają daty: ruszają po akceptacji.",
    poprzedni: "Poprzedni pakiet",
    nastepny: "Następny pakiet",
    okres: "Okres",
    brak: "Nie ma zaplanowanych publikacji w tym okresie.",
    brakPakietu: "Nie ma jeszcze pakietu z harmonogramem. Gdy przygotujemy materiały, zobaczysz tu daty publikacji.",
    lista: "Lista publikacji",
    kampanie: "Kampanie w tym okresie",
    bezKampanii: "W tym okresie nie ma kampanii reklamowej.",
    skomentuj: "Skomentuj",
    zobacz: "Zobacz",
    bezDaty: "Jeszcze bez daty",
    dniTygodnia: ["Pn", "Wt", "Śr", "Cz", "Pt", "So", "Nd"],
    statusy: { szkic: "szkic", do_akceptacji: "do akceptacji", poprawki: "poprawki", zaakceptowany: "zaakceptowany", zaplanowany: "zaplanowany" },
    typ: { post: "Post", relacja: "Relacja", reels: "Reels", reklama: "Reklama" },
    cel: "Cel:",
  },
  /** „Zobacz jak klient" (SPEC rozdz. 2, kryterium 25): stały pasek, tryb wyłącznie do odczytu. */
  podgladKlienta: {
    przycisk: "Zobacz jak klient",
    pasek: "PODGLĄD KLIENTA - {nazwa}",
    pasekOpis: "Widzisz panel tak, jak widzi go klient. Nic tu nie zapiszesz.",
    wyjdz: "Wyjdź",
    niedostepne: "niedostępne w podglądzie",
    decyzjeZablokowane: "Przyciski decyzji są niedostępne w podglądzie. Decyzję podejmuje klient.",
    komentarzeZablokowane: "W podglądzie nie da się dodać uwagi. Odpowiedzi klientowi wysyłasz z panelu zespołu.",
    zalogowanyJako: "Podgląd zespołu",
    blad: "Podgląd klienta jest dostępny wyłącznie w trybie odczytu.",
  },
  stopka: {
    regulamin: "Regulamin",
    prywatnosc: "Polityka prywatności",
    prawa: "Foodie Media",
  },
  nieZnaleziono: {
    tytul: "Nie ma takiej strony",
    opis: "Sprawdź link, który dostałeś od opiekuna, albo wróć na stronę główną.",
    wroc: "Wróć na stronę główną",
  },
  zespol: {
    logowanie: {
      tytul: "Panel zespołu",
      opis: "Zaloguj się adresem e-mail. Wyślemy Ci kod, który wpiszesz poniżej.",
      email: "Adres e-mail",
      wyslijKod: "Wyślij kod",
      wysylanie: "Wysyłamy...",
      kodWyslany: "Jeśli ten adres jest na liście zespołu, wysłaliśmy na niego kod. Sprawdź skrzynkę i wpisz go poniżej.",
      kod: "Kod z e-maila",
      zaloguj: "Zaloguj się",
      sprawdzanie: "Sprawdzamy...",
      zlyKod: "Kod się nie zgadza albo wygasł. Przepisz wszystkie cyfry z maila albo wyślij nowy kod.",
      innyAdres: "Użyj innego adresu",
      zbytWiele: "Za dużo prób. Odczekaj chwilę i spróbuj ponownie.",
      brakDostepu: "Ten adres nie ma dostępu do panelu zespołu. Zostałeś wylogowany. Jeśli to pomyłka, poproś admina o dodanie Cię do zespołu.",
    },
    nawigacja: {
      pulpit: "Pulpit",
      klienci: "Klienci",
      skrzynka: "Skrzynka uwag",
      ustawienia: "Ustawienia",
      powiadomienia: "Powiadomienia",
      retencja: "Retencja",
      wyloguj: "Wyloguj",
    },
    role: {
      admin: "Admin",
      csm: "Opiekun klienta",
      content_creator: "Content creator",
      media_buyer: "Media buyer",
      sales: "Sprzedaż",
    },
    kategorie: {
      kat1: "Kategoria 1: osobne restauracje",
      kat2: "Kategoria 2: sieć, jeden profil",
      kat3: "Kategoria 3: sieć, osobne profile",
    },
    kategorieKrotko: { kat1: "kat. 1", kat2: "kat. 2", kat3: "kat. 3" },
    pakiety: { foodie_one: "Foodie One", foodie_360: "Foodie 360°", siec: "Sieć" },
    pulpit: {
      tytul: "Pulpit",
      opis: "Klienci, których obsługujesz, i to, co u nich czeka.",
      brakKlientow: "Nie masz jeszcze przypisanych klientów. Poproś admina o przypisanie.",
      kolumny: { klient: "Klient", kategoria: "Kategoria", pakiet: "Pakiet", doAkceptacji: "Do akceptacji", linki: "Aktywne linki" },
      otworz: "Otwórz kartę",
      miesiecznie: "mies. netto",
      nieaktywni: "Przerwy i zakończone współprace",
      nieaktywniOpis: "Nie ma ich na pulpicie, ale karta klienta działa: można wznowić współpracę albo usunąć dane.",
      usunietoKlienta: "Dane klienta {klient} zostały usunięte.",
    },
    karta: {
      demo: "klient demonstracyjny",
      lokale: "Lokale",
      kontakty: "Osoby kontaktowe",
      slack: "Slack",
      opiekun: "Opiekun",
      brakOpiekuna: "nie przypisano",
      wspolpracaOd: "Współpraca od",
      zakladki: {
        materialy: "Materiały",
        harmonogram: "Harmonogram",
        raporty: "Raporty",
        faktury: "Faktury",
        dokumenty: "Dokumenty",
        dostep: "Dostęp",
        ustawienia: "Dane i współpraca",
        wdrozenie: "Wdrożenie (wkrótce)",
      },
      wkrotce: "Ta zakładka powstaje w kolejnym etapie.",
      wdrozenieWkrotce: "Wdrożenie klienta jest przygotowane, ale wyłączone (flaga onboarding_enabled).",
      statusKlienta: { aktywny: "Współpraca trwa", wstrzymany: "Przerwa we współpracy", zakonczony: "Współpraca zakończona" },
      zakonczonaOd: "zakończona {data}",
      podsumowanie: "Podsumowanie",
      kontaktDlaKlienta: "Kontakt dla klienta",
      zainteresowania: {
        tytul: "Zainteresowanie usługami",
        opis: "Klient kliknął „Chcę wiedzieć więcej\" w panelu. Powiadomienie poszło też na Slacka przez Zapiera.",
        brak: "Klient nie zgłosił jeszcze zainteresowania żadną usługą.",
        zalatwione: "Załatwione",
        oznacz: "Oznacz jako załatwione",
        zalatwilOsoba: "załatwione {data}",
        ktoZglosil: "{osoba}, {data}",
        bezNotatki: "bez wiadomości",
      },
    },
    pulpitPakiety: {
      tytul: "Pakiety w toku",
      opis: "Wszystkie pakiety poza zaplanowanymi. Pakiet z wstrzymaną auto-akceptacją ma osobny, bursztynowy wiersz.",
      brak: "Żaden pakiet nie czeka na decyzję.",
      kolumny: { klient: "Klient", okres: "Okres", status: "Status", wyslano: "Wysłano", czeka: "Czeka", auto: "Auto-akcept za", uwagi: "Uwagi", akcja: "Akcja" },
      wstrzymana: "Auto-akceptacja wstrzymana",
      nieprzeczytane: "{n} nieprzeczytane",
      nierozwiazane: "{n} nierozwiązane",
      bezUwag: "0",
      odpowiedz: "Odpowiedz na uwagi",
      otworz: "Otwórz pakiet",
      temu: "{czas} temu",
      dni: { jeden: "dzień", kilka: "dni", wiele: "dni" },
      godziny: { jeden: "godz.", kilka: "godz.", wiele: "godz." },
      auto: { za: "za", minal: "minął", zatrzymane: "zatrzymane", wylaczona: "wyłączona", brak: "-" },
      filtry: {
        zakres: "Zakres",
        moi: "Moi klienci",
        wszyscy: "Wszyscy klienci",
        status: "Status",
        wszystkieStatusy: "Wszystkie statusy",
        miesiac: "Miesiąc startu",
        wszystkieMiesiace: "Wszystkie miesiące",
        pokaz: "Pokaż",
        wyczysc: "Wyczyść",
      },
      pokazLink: "Pokaż link",
      pokazLinkTytul: "Link dostępu klienta",
      pokazLinkOpis: "Wybierz osobę. Każde pokazanie linku zapisuje się w historii dostępu.",
      pokazLinkBrak: "Ten klient nie ma aktywnego linku. Utwórz go w zakładce Dostęp.",
      zobaczUwagi: "Zobacz uwagi",
    },
    pakietyMaterialow: {
      tytul: "Materiały",
      opis: "Pakiety tego klienta, każdy na okres od-do (np. 20.09 do 19.10). Nowy pakiet zakładasz w kreatorze na wklejanych linkach do folderów na Dysku.",
      brak: "Ten klient nie ma jeszcze pakietów materiałów.",
      kolumny: { okres: "Okres", status: "Status", wyslano: "Wysłano", auto: "Auto-akceptacja", uwagi: "Uwagi" },
      otworz: "Otwórz pakiet",
      wroc: "Wróć do listy pakietów",
      akcje: {
        tytul: "Akcje zespołu",
        wyslij: "Wyślij do akceptacji",
        wycofaj: "Wycofaj do szkicu",
        wyslijV2: "Wyślij wersję {n}",
        cofnij: "Cofnij do poprawek",
        zaplanowano: "Zaplanowano",
        autoCheckbox: "Automatyczna akceptacja po terminie",
        autoOpis: "Domyślnie z karty klienta. Odznacz, gdy ten pakiet ma czekać na ręczną decyzję.",
        powod: "Powód cofnięcia",
        powodOpis: "Klient zobaczy ten tekst w bursztynowym banerze zamiast zielonego „Zaakceptowano\".",
        powodPodpowiedz: "np. Zła cena w poście 3, poprawiamy grafikę",
        potwierdzCofniecie: "Cofnij do poprawek",
        anuluj: "Anuluj",
        trwa: "Zapisujemy...",
        wycofajPotwierdz: "Wycofać pakiet do szkicu? Klient przestanie go widzieć, licznik zniknie.",
        zaplanowanoPotwierdz: "Oznaczyć jako zaplanowany? Potwierdzasz, że publikacje są ustawione w Meta Business Suite.",
        wyslanoV2Info: "Wysyłka nowej wersji działa też bez zmian w materiałach (klient napisał, że jednak jest dobrze).",
      },
      braki: "Uzupełnij braki przed wysyłką:",
      ostrzezenia: "Ostrzeżenia (nie blokują wysyłki):",
      odpowiedz: "Odpowiedz",
      odpowiedzPodpowiedz: "Odpowiedź zobaczy klient w tym samym miejscu, pod swoją uwagą.",
      wyslijOdpowiedz: "Wyślij odpowiedź",
      zalatwione: "Oznacz jako załatwione",
      zalatwioneOpis: "Załatwione uwagi nie wstrzymują auto-akceptacji.",
      nierozwiazane: "{n} nierozwiązanych uwag klienta w tej rundzie",
      wstrzymana: "Auto-akceptacja wstrzymana",
      wstrzymanaOpis: "Termin minął, ale klient ma nierozwiązane uwagi. Odpowiedz i oznacz je jako załatwione (cron zatwierdzi przy następnym przebiegu) albo cofnij do poprawek.",
      autoTermin: "Termin auto-akceptacji:",
      autoWylaczona: "Auto-akceptacja wyłączona dla tego pakietu.",
      wyslanoV: "Wysłano {data}, wersja {n}.",
      zaakceptowano: "Zaakceptowano {data} ({rodzaj}) przez {osoba}.",
      rodzajAkceptacji: { reczna: "ręcznie", automatyczna: "automatycznie" },
      nikt: "panel",
    },
    /** Narzędzia nad materiałami w panelu zespołu (SPEC rozdz. 12.6). */
    materialy: {
      dodajMaterial: "Dodaj materiał",
      dodajKampanie: "Dodaj kampanię",
      edytuj: "Edytuj",
      podmien: "Podmień",
      pliki: "Pliki",
      usun: "Usuń",
      usunPotwierdz: "Usunąć ten materiał razem z plikami? Tego nie da się cofnąć.",
      usunKampaniePotwierdz: "Usunąć kampanię razem z reklamą i grafikami? Tego nie da się cofnąć.",
      tylkoSzkic: "Usuwanie działa tylko w szkicu. Po wysyłce podmień plik albo cofnij pakiet do szkicu.",
      nowy: {
        tytul: "Nowy materiał",
        opis: "Plik z komputera albo link do pojedynczego pliku na Dysku.",
        typ: "Rodzaj",
        kampania: "Kampania",
        kampaniaOpis: "Reklama trafia do istniejącej kampanii jako kolejna grafika.",
        tytulPola: "Robocza nazwa",
        tytulPodpowiedz: "np. Post 7 - nowa pizza",
        pozycja: "Pozycja",
        pozycjaOpis: "Puste = na końcu listy.",
        plik: "Plik",
        dodaj: "Dodaj",
      },
      podmiana: {
        tytul: "Pliki materiału",
        opis: "Podmiana zachowuje stary plik w historii oraz wszystkie uwagi klienta. Pozycja materiału zostaje.",
        podmienPlik: "Podmień",
        dodajSlajd: "Dodaj slajd",
        dodajGrafike: "Dodaj grafikę",
        usunPlik: "Usuń",
        usunPlikPotwierdz: "Usunąć ten plik z materiału? Zostanie w historii, ale klient go już nie zobaczy.",
        ostatniPlik: "To ostatni plik tego materiału. Najpierw dodaj nowy, potem usuń stary.",
        wybierz: "Wybierz plik",
        wybierzNowy: "Wybierz nowy plik",
        slajd: "Slajd {n}",
        grafika: "Grafika {n}",
        wideo: "Wideo",
      },
      edycja: {
        tytul: "Edycja materiału",
        tytulPola: "Robocza nazwa",
        opis: "Opis posta / tekst relacji",
        opisPodpowiedz: "Tekst, który klient zobaczy w podglądzie tak, jak na Facebooku.",
        publikacja: "Data i godzina publikacji",
        bezDaty: "Bez daty (materiał niezaplanowany)",
        lokale: "Publikujemy na",
        zapisz: "Zapisz",
        anuluj: "Anuluj",
        bezZmian: "Nic się nie zmieniło.",
      },
      reklama: {
        tytul: "Teksty i nagłówki reklamy",
        opis: "Klient przełącza w podglądzie każdą kombinację grafiki, tekstu i nagłówka. Grafiki dodajesz przez „Pliki\".",
        teksty: "Teksty",
        naglowki: "Nagłówki",
        dodajTekst: "Dodaj tekst",
        dodajNaglowek: "Dodaj nagłówek",
        usunWiersz: "Usuń",
        opisPola: "Opis (pod nagłówkiem)",
        cta: "Przycisk",
        link: "Link (wspólny)",
        perLokal: "Wersje per lokal",
        perLokalOpis: "Puste pole = wersja wspólna. Wypełnij tylko to, co różni się w danym lokalu (najczęściej link).",
        linkLokalu: "Link",
        ctaLokalu: "Przycisk",
        opisLokalu: "Opis",
        wspolny: "wspólny",
        zapisz: "Zapisz reklamę",
      },
      kampania: {
        tytulNowa: "Nowa kampania",
        tytulEdycja: "Kampania",
        nazwa: "Nazwa",
        nazwaPodpowiedz: "np. Kampania standardowa, Imprezy okolicznościowe",
        cel: "Cel",
        bezCelu: "Bez celu",
        notatka: "Zdanie dla klienta",
        notatkaPodpowiedz: "Po co ta kampania, np. chcemy dowozić rezerwacje na urodziny i komunie.",
        folder: "Link do folderu z reklamami na Dysku",
        folderOpis: "Grafiki oraz dokument z tekstami i nagłówkami. Osobny folder na każdą kampanię.",
        zapisz: "Zapisz kampanię",
        dodaj: "Dodaj kampanię",
      },
      potwierdzenie: {
        tytul: "Ten materiał jest już zaakceptowany",
        opis: "Klient zaakceptował ten pakiet. Po zmianie materiał dostanie plakietkę, klient zobaczy baner o podmianie, a zespół dostanie powiadomienie.",
        checkbox: "Rozumiem, zmieniam zaakceptowany materiał",
        wymagane: "Zaznacz, że zmieniasz zaakceptowany materiał.",
      },
      upload: {
        wybierz: "Wybierz plik z komputera",
        formaty: "JPG, PNG, WEBP, HEIC do 25 MB albo MP4, MOV do 300 MB.",
        wysylanie: "Wysyłamy plik... {procent}%",
        sprawdzanie: "Sprawdzamy plik i robimy podglądy...",
        gotowy: "Plik gotowy: {nazwa}",
        duzeWideo: "Wideo waży ponad 150 MB. Wyślij, ale sprawdź, czy da się je odchudzić.",
        bezPodgladu: "Nie udało się zrobić podglądu (format HEIC). Klient zobaczy oryginał, jeśli jego przeglądarka go otworzy.",
        bledy: {
          nieobslugiwany: "Ten format nie jest obsługiwany. Wyślij JPG, PNG, WEBP, HEIC, MP4 albo MOV.",
          zaDuzy: "Plik jest za duży. Limit: {limit}.",
          niezgodnyZDeklaracja: "Zawartość pliku nie zgadza się z jego rozszerzeniem. Sprawdź, co wysyłasz.",
          pozwolenie: "Pozwolenie na wysyłkę wygasło. Wybierz plik jeszcze raz.",
          brakPliku: "Plik nie dotarł do magazynu. Sprawdź połączenie i spróbuj ponownie.",
          przetwarzanie: "Nie udało się przetworzyć obrazu. Spróbuj zapisać go ponownie jako JPG.",
          wysylka: "Wysyłka pliku się nie powiodła. Sprawdź połączenie i spróbuj ponownie.",
        },
      },
      bledy: {
        brak_materialu: "Nie znaleziono materiału. Odśwież stronę.",
        brak_pliku: "Nie znaleziono pliku. Odśwież stronę.",
        zly_typ: "Ta operacja nie dotyczy tego rodzaju materiału.",
        brak_kampanii: "Wybierz kampanię, do której trafi reklama.",
        ostatni_plik: "To ostatni plik tego materiału. Najpierw dodaj nowy, potem usuń stary.",
        tylko_szkic: "To działa tylko w szkicu.",
        zle_dane: "Sprawdź wypełnione pola.",
        wymaga_potwierdzenia: "Zaznacz, że zmieniasz zaakceptowany materiał.",
        ogolny: "Nie udało się zapisać. Odśwież stronę i spróbuj ponownie.",
      },
      zapisano: "Zapisano.",
      zapisanoPlakietka: { nowe: "Zapisano. Klient zobaczy plakietkę „Nowe\".", poprawione: "Zapisano. Klient zobaczy plakietkę „Poprawione\"." },
      zapisanoTermin: "Termin auto-akceptacji przesunięty na {termin}.",
    },
    /** Kreator pakietu na wklejanych linkach (SPEC rozdz. 12.3). */
    kreator: {
      tytul: "Nowy pakiet materiałów",
      opis: "Pakiet powstaje w szkicu. Wklej linki do folderów na Dysku (osobny folder z contentem, osobny folder z reklamami dla każdej kampanii). Zaraz potem zobaczysz kartę weryfikacyjną każdego folderu i ekran mapowania; import kopiuje pliki w tle.",
      nowyPakiet: "Nowy pakiet",
      krokKlient: "1. Klient i okres",
      krokContent: "2. Folder z contentem",
      krokKampanie: "3. Kampanie",
      od: "Od",
      do: "Do",
      okresOpis: "Okres, na który przygotowujemy materiały, np. 20.09 do 19.10. Wpisz obie daty; kolejny pakiet może zacząć się dowolnego dnia.",
      miesiacWspolpracyPole: "Miesiąc współpracy",
      miesiacWspolpracyOpis: "Podpowiadamy numer o jeden większy niż w ostatnim pakiecie klienta. Po przerwie we współpracy popraw go ręcznie.",
      okresNachodzi: "Ten okres zachodzi na inny pakiet klienta: {pakiety}. Sprawdź daty, jeśli to nie jest celowe.",
      lokal: "Lokal",
      lokalOpis: "Klient z osobnymi restauracjami ma osobny pakiet na każdy lokal.",
      lokalWspolny: "Jeden pakiet dla wszystkich lokali (kategoria 2 i 3).",
      tytulPakietu: "Tytuł",
      miesiacWspolpracy: "{n}. miesiąc współpracy",
      folderContentu: "Link do folderu z contentem na Dysku",
      folderContentuOpis: "Folder „content {N} mies\" z podfolderami „1. Posty\" i „2. Relacje\". Panel nie zgaduje ścieżek: albo wklejasz link, albo folderu nie ma.",
      linkRozpoznany: "Rozpoznano folder o identyfikatorze {id}.",
      linkNierozpoznany: "To nie wygląda na link do folderu na Dysku Google.",
      importPoUtworzeniu: "Po utworzeniu pakietu przejdziesz do karty weryfikacyjnej tego folderu. Panel nie zgaduje ścieżek na Dysku: importuje wyłącznie to, co wkleisz.",
      kampanieOpis: "Kampanii bywa kilka w jednym pakiecie: standardowa, na imprezy okolicznościowe, na polubienia strony. Każda ma własny folder z reklamami.",
      bezKampanii: "Pakiet bez kampanii da się wysłać, ale dostaniesz ostrzeżenie przy wysyłce.",
      usunKampanie: "Usuń kampanię",
      utworz: "Utwórz pakiet",
      tworzenie: "Tworzymy...",
      anuluj: "Anuluj",
      bledy: {
        zlyLink: "To nie jest link do folderu na Dysku Google. Wklej adres z paska przeglądarki.",
        brakLokalu: "Wybierz lokal, którego dotyczy pakiet.",
        brakNazwyKampanii: "Każda kampania musi mieć nazwę.",
        brakOkresu: "Wpisz datę początku i datę końca okresu.",
        zlyOkres: "Data zakończenia nie może być wcześniejsza niż data początku.",
        zaDlugiOkres: "Okres pakietu może trwać najwyżej rok. Sprawdź daty.",
      },
    },
    import: {
      tytul: "Import z Dysku",
      opis: "Trzy kroki: sprawdzasz kartę weryfikacyjną każdego folderu, potwierdzasz, która grafika ma który opis, a potem panel kopiuje pliki w tle. Nic nie trafia do bazy bez Twojego potwierdzenia.",
      nieSkonfigurowany: "Import z Dysku nie jest jeszcze skonfigurowany na tym serwerze (konto usługi Google). Materiały dodasz przyciskiem „Dodaj materiał\".",
      tylkoSzkic: "Import z Dysku działa w szkicu. Po wysyłce dodawaj i podmieniaj materiały pojedynczo, także linkiem do pliku na Dysku.",
      bezFolderow: "Ten pakiet nie ma jeszcze linków do folderów. Wklej link do folderu z contentem albo do folderu z reklamami przy kampanii.",
      przyciskWPakiecie: "Importuj z Dysku",
      krokWeryfikacja: "1. Karta weryfikacyjna",
      krokMapowanie: "2. Mapowanie: grafika i opis",
      krokImport: "3. Kopiowanie plików",
      karta: {
        content: "Folder z contentem",
        reklamy: "Folder z reklamami: {kampania}",
        brakLinku: "Bez linku. Wklej link do folderu, żeby go zaimportować, albo zostaw pusty: ten folder zostanie pominięty.",
        nieZnaleziono: "Nie znaleziono folderu albo konto usługi go nie widzi. Sprawdź link i udostępnienie folderu „Materiały klientów\" dla konta usługi.",
        zablokowany: "Ten folder leży poza „Materiałami klientów\". Import zablokowany, bez obejścia. Wklej link do folderu z właściwego miejsca na Dysku.",
        sciezka: "Ścieżka na Dysku",
        pliki: "Pliki",
        plikiOpis: "{obrazy} grafik, {wideo} wideo, {dokumenty} dokumentów, {inne} innych",
        zmodyfikowano: "Ostatnia zmiana",
        pierwsze: "Pierwsze pliki",
        podfoldery: "Podfoldery",
        posty: "Posty",
        relacje: "Relacje",
        brakPodfolderu: "brak",
        ostrzezenia: "Ostrzeżenia",
        ostrzezenie: {
          klient: "Folder klienta na Dysku nazywa się „{folder}\", a wybrany klient to „{klient}\". Upewnij się, że to właściwy klient.",
          miesiac: "W nazwie folderu jest miesiąc {wNazwie}, a ten pakiet to {oczekiwany}. miesiąc współpracy. Sprawdź, czy to właściwy miesiąc.",
          miesiacKalendarzowy: "W nazwie folderu jest „{wNazwie}\", a ten pakiet zaczyna się w miesiącu {oczekiwany}.",
          okres: "W nazwie folderu jest okres {wNazwie}, a ten pakiet zaczyna się w {oczekiwany}. Sprawdź, czy to właściwy okres.",
          powtorny: "Ten folder był już użyty w pakiecie „{tytul}\" ({okres}){data}. To główne zabezpieczenie przed materiałami z innego miesiąca.",
          powtornyData: ", import {data}",
          powtornyLink: "Otwórz tamten pakiet",
          brakPodfolderow: "W folderze nie ma podfolderów „1. Posty\" i „2. Relacje\". Wszystkie grafiki potraktujemy jak posty; relacje przestawisz w mapowaniu.",
          pusty: "Folder jest pusty.",
          nieobslugiwane: "Pominiemy pliki w nieobsługiwanym formacie: {nazwy}. Panel przyjmuje JPG, PNG, WEBP, HEIC, MP4 i MOV.",
          duzeWideo: "Wideo powyżej 150 MB: {nazwy}. Zaimportujemy, ale sprawdź, czy da się je odchudzić.",
        },
        bladLimitu: "Import przerwany: plik „{nazwa}\" waży {waga}, a limit to {limit}. Zmniejsz plik na Dysku i sprawdź folder ponownie.",
        bladDysku: "Nie udało się odczytać folderu z Dysku: {komunikat}",
        ignoruj: "Rozumiem ostrzeżenia i importuję mimo to",
        ignorujWymagane: "Zaznacz przy każdym folderze z ostrzeżeniami, że je rozumiesz, albo popraw link.",
        zmienLink: "Zmień link",
        anulujZmiane: "Anuluj",
        zapiszLink: "Zapisz i sprawdź ponownie",
        sprawdzPonownie: "Sprawdź ponownie",
        pomin: "Pomiń ten folder",
        pominiety: "Folder pominięty. Materiały z niego dodasz później.",
        przywroc: "Jednak importuj",
      },
      dalej: "Dalej: mapowanie",
      dalejBrak: "Żaden folder nie nadaje się do importu. Popraw linki albo dodaj materiały ręcznie.",
      przygotowujemy: "Czytamy foldery i dokumenty...",
      mapowanie: {
        tytul: "Mapowanie",
        opis: "Sprawdź, która grafika ma który opis, i popraw, co trzeba. Nic nie trafi do bazy, dopóki nie klikniesz „Importuj\".",
        posty: "Posty i Reels",
        relacje: "Relacje",
        brakMaterialow: "Brak grafik ani wideo w tym folderze.",
        rodzaj: "Rodzaj",
        rodzaje: { post: "Post", reels: "Reels", relacja: "Relacja" },
        tytulPola: "Robocza nazwa",
        opisPola: "Opis",
        opisZDokumentu: "Opis z dokumentu",
        bezOpisu: "Bez opisu (uzupełnisz w edycji materiału)",
        wybierzOpis: "Wybierz opis",
        dopasowanie: { numer: "Dopasowano po numerze", dokument: "Dopasowano po numerze w nazwie dokumentu", kolejnosc: "Dopasowano po kolejności, sprawdź", brak: "Bez opisu" },
        pliki: "{n} plików",
        slajdy: "Karuzela: {n} slajdów",
        pomin: "Pomiń",
        przywroc: "Przywróć",
        pominiety: "Pominięty",
        podzialDokumentu: "Podgląd podziału dokumentu „{nazwa}\"",
        sekcja: "Sekcja {numer}",
        sekcjaBezNumeru: "Sekcja bez numeru",
        wstep: "Tekst przed pierwszym nagłówkiem",
        nieuzyte: "Opisy, które nie trafiły do żadnego materiału",
        reklama: "Reklama: {kampania}",
        grafiki: "Grafiki",
        teksty: "Teksty",
        naglowki: "Nagłówki",
        opisReklamy: "Opis (pod nagłówkiem)",
        cta: "Przycisk",
        link: "Link",
        zDokumentu: "Z dokumentu: {nazwy}",
        bezSekcji: "Dokument nie ma sekcji „Teksty\" i „Nagłówki\", więc wszystko trafiło do tekstów. Popraw ręcznie.",
        bezDokumentu: "W folderze nie ma dokumentu z tekstami. Uzupełnisz je w edycji reklamy.",
        dodajTekst: "Dodaj tekst",
        dodajNaglowek: "Dodaj nagłówek",
        usun: "Usuń",
        podsumowanie: "Do importu: {materialy} materiałów i {pliki} plików.",
        importuj: "Importuj",
        importujemy: "Uruchamiamy import...",
        wstecz: "Wróć do weryfikacji",
        nicDoImportu: "Nic do importu. Przywróć przynajmniej jeden materiał albo grafikę.",
      },
      postep: {
        tytul: "Kopiowanie plików",
        opis: "Import idzie w tle. Możesz zamknąć tę stronę; postęp zobaczysz po powrocie.",
        rodzaj: { content: "Content", reklamy: "Reklamy: {kampania}", dodatkowy: "Dodatkowy materiał", podmiana: "Podmiana" },
        status: { oczekuje: "Czeka w kolejce", trwa: "Trwa", zakonczony: "Zakończony", blad: "Błąd" },
        pliki: "{gotowe} z {razem} plików",
        zawieszone: "Import się zatrzymał (serwer przerwał pracę w połowie). Wznów, żeby dokończyć od miejsca, w którym stanął.",
        wznow: "Wznów import",
        ponow: "Ponów",
        ostrzezenia: "Ostrzeżenia",
        gotowe: "Import zakończony. Uzupełnij daty publikacji w harmonogramie i sprawdź podgląd oczami klienta.",
        otworzPakiet: "Otwórz pakiet",
        nowyImport: "Nowy import",
      },
      bledy: {
        zablokowany: "Jeden z folderów leży poza „Materiałami klientów\". Import zablokowany.",
        zle_dane: "Dane mapowania nie zgadzają się z zawartością folderu. Wróć do weryfikacji i spróbuj ponownie.",
        nic_do_importu: "Nic do importu.",
        tylko_szkic: "Import z Dysku działa tylko w szkicu.",
        w_toku: "Poprzedni import jeszcze trwa. Poczekaj, aż się skończy.",
        nie_skonfigurowany: "Import z Dysku nie jest skonfigurowany na tym serwerze.",
        brak_kampanii: "Kampania z mapowania nie istnieje już w pakiecie. Odśwież stronę.",
        dysk: "Dysk nie odpowiada: {komunikat}",
        pobieranie: "Nie udało się pobrać pliku „{nazwa}\" z Dysku.",
        magia: "Plik „{nazwa}\" nie jest obrazem ani wideo w obsługiwanym formacie.",
        limit: "Import przerwany: plik „{nazwa}\" waży {waga}, a limit to {limit}.",
        brak_reklamy: "Kampania nie ma materiału reklamowego. Odśwież stronę.",
        ogolny: "Import przerwany przez błąd serwera. Ponów; jeśli błąd się powtórzy, napisz do Szymona.",
      },
      ostrzezeniaZadania: {
        juzWPakiecie: "Pominięto „{nazwa}\": ten plik z Dysku jest już w pakiecie.",
        bezPodgladu: "„{nazwa}\": nie udało się zrobić podglądu (HEIC). Klient zobaczy oryginał, jeśli jego przeglądarka go otworzy.",
        duzeWideo: "„{nazwa}\" waży ponad 150 MB.",
        powtorzonyTekst: "Pominięto powtórzony tekst albo nagłówek reklamy.",
      },
      plikZDysku: {
        etykieta: "albo wklej link do pliku na Dysku",
        pobierz: "Pobierz z Dysku",
        pobieranie: "Pobieramy plik z Dysku...",
        bledy: {
          zlyLink: "To nie jest link do pliku na Dysku Google.",
          folder: "To link do folderu. Do pojedynczego materiału wklej link do pliku (Udostępnij, Kopiuj link).",
          nieZnaleziono: "Nie znaleziono pliku albo konto usługi go nie widzi.",
          zablokowany: "Ten plik leży poza „Materiałami klientów\". Panel nie importuje plików spoza nich.",
          nieSkonfigurowany: "Import z Dysku nie jest skonfigurowany na tym serwerze.",
          dysk: "Dysk nie odpowiada. Spróbuj za chwilę.",
        },
      },
    },
    /** Harmonogram zespołu (SPEC rozdz. 8): przeciąganie po kalendarzu i panel „Niezaplanowane". */
    harmonogram: {
      tytul: "Harmonogram",
      opis: "Przeciągnij materiał na dzień publikacji albo ustaw datę w polu obok. Kampanie reklamowe nie mają daty i są poza kalendarzem.",
      poprzedni: "Poprzedni pakiet",
      nastepny: "Następny pakiet",
      niezaplanowane: "Niezaplanowane",
      niezaplanowaneOpis: "Materiały bez daty publikacji. Każdy post i każda relacja musi mieć datę przed wysyłką do akceptacji.",
      wszystkoZaplanowane: "Wszystkie materiały mają datę.",
      pozaOkresem: "Poza tym okresem",
      pozaOkresemOpis: "Materiały z datą poza okresem pakietu. Przeciągnij je na dzień w siatce albo zmień okres w ustawieniach.",
      kampanie: "Kampanie reklamowe w tym okresie",
      bezKampanii: "Brak kampanii.",
      brakPakietow: "Ten klient nie ma jeszcze pakietu. Załóż go w zakładce Materiały.",
      pakiet: "Pakiet",
      okresPakietu: "Okres pakietu",
      od: "Od",
      do: "Do",
      okresPakietuOpis: "Od pierwszego do ostatniego dnia publikacji z planu contentu. Siatka kalendarza obejmuje ten okres; kolejny pakiet może zacząć się dowolnego dnia.",
      godzinyDomyslne: "Domyślne godziny publikacji",
      godzinyDomyslneOpis: "Materiał upuszczony na dzień dostaje pierwszą wolną z tych godzin. Wpisz godziny po przecinku, np. 12, 18.",
      godzina: "Godzina",
      data: "Data",
      ustaw: "Ustaw",
      usunDate: "Bez daty",
      upuscTutaj: "Upuść tutaj",
      przeciagnij: "Przeciągnij, żeby zmienić dzień",
      zapisywanie: "Zapisujemy...",
      podglad: "Podgląd",
      typ: { post: "Post", relacja: "Relacja", reels: "Reels", reklama: "Reklama" },
      bledy: { zlaData: "Wpisz poprawną datę.", zlyOkres: "Data zakończenia nie może być wcześniejsza niż data początku, a okres nie może trwać dłużej niż rok.", zleGodziny: "Wpisz od 1 do 6 godzin z zakresu 0-23, po przecinku." },
      },
    /** Skrzynka uwag (SPEC rozdz. 12.5). */
    skrzynka: {
      tytul: "Skrzynka uwag",
      opis: "Nierozwiązane uwagi klientów ze wszystkich pakietów. Odpowiadasz stąd i oznaczasz „Załatwione\".",
      brak: "Nie ma nierozwiązanych uwag. Wszystko załatwione.",
      filtrKlient: "Klient",
      filtrTyp: "Rodzaj",
      wszyscy: "Wszyscy klienci",
      wszystkieTypy: "Wszystkie rodzaje",
      doPakietu: "Cały pakiet",
      typ: { post: "Post", relacja: "Relacja", reels: "Reels", reklama: "Reklama", pakiet: "Cały pakiet" },
      otworzPakiet: "Otwórz pakiet",
      odpowiedzi: "{n} odp.",
      poAkceptacji: "po akceptacji",
      nieprzeczytana: "nowa",
      oznaczPrzeczytana: "Oznacz jako przeczytaną",
      liczba: "{n} do załatwienia",
      filtruj: "Filtruj",
    },
    dostep: {
      tytul: "Dostęp klienta",
      opis: "Każda osoba po stronie klienta dostaje własny link i jednorazowy kod startowy, a przy pierwszym wejściu ustawia własny PIN. Dzięki temu widzisz, kto zaakceptował materiały.",
      utworz: "Utwórz link",
      brakLinkow: "Ten klient nie ma jeszcze żadnego linku. Utwórz pierwszy.",
      kolumny: { osoba: "Osoba", utworzono: "Utworzono", ostatnieWejscie: "Ostatnie wejście", status: "Status", urzadzenia: "Urządzenia" },
      status: { aktywny: "Aktywny", wygaszony: "Wygaszony", zablokowany: "Zablokowany do", tylkoPodglad: "tylko podgląd", zamrozony: "Zamrożony po próbach zgadnięcia PIN-u" },
      /** Stan PIN-u linku (Etap 2): kod startowy czeka, wygasł, klient ustawił własny PIN. */
      pinStan: {
        czeka: "Czeka na PIN klienta, kod ważny do {data}",
        czekaBezTerminu: "Czeka na PIN klienta",
        kodWygasl: "Kod startowy wygasł, wydaj nowy",
        ustawiony: "PIN ustawiony przez klienta {data}",
      },
      nigdy: "jeszcze nie",
      demo: "To klient demonstracyjny do pokazywania panelu. Nie wystawiamy mu linków dostępu ani faktur. Zespół ogląda go przez „Zobacz jak klient\".",
      zakonczony: "Współpraca z tym klientem jest zakończona, linki są wygaszone. Żeby utworzyć nowy link, wznów współpracę w zakładce Dane i współpraca.",
      akcje: {
        pokazLink: "Pokaż link",
        ukryjLink: "Ukryj",
        kopiujLink: "Kopiuj link",
        wygas: "Wygaś link",
        wygasPotwierdz: "Wygasić ten link? Osoba straci dostęp przy następnym wejściu. Tego nie da się cofnąć.",
        wylogujUrzadzenia: "Wyloguj wszystkie urządzenia",
        wylogujPotwierdz: "Wylogować wszystkie urządzenia tego linku? Osoba będzie musiała ponownie wpisać PIN.",
        resetujPin: "Wydaj nowy kod",
        resetujPotwierdz: "Wydać nowy kod startowy? Obecny PIN przestanie działać, wszystkie urządzenia zostaną wylogowane, a klient po wpisaniu kodu ustawi nowy PIN. Kod zobaczysz tylko raz.",
      },
      nowy: {
        tytul: "Nowy link dostępu",
        osoba: "Osoba kontaktowa",
        innaOsoba: "Inna osoba (wpisz opis)",
        etykieta: "Opis linku",
        etykietaPodpowiedz: "np. Marek - właściciel",
        mozeAkceptowac: "Ta osoba może akceptować materiały",
        tylkoPodgladOpis: "Bez zaznaczenia: link tylko do podglądu i komentarzy, bez przycisków decyzji.",
        utworz: "Utwórz",
        tworzenie: "Tworzymy...",
        anuluj: "Anuluj",
      },
      gotowy: {
        tytul: "Link i kod startowy gotowe",
        opis: "Kod widzisz tylko teraz. Działa raz i przez 7 dni: klient wpisze go przy pierwszym wejściu i ustawi własny PIN. Link i kod wyślij osobnymi wiadomościami (np. na WhatsAppie); wiadomość piszesz sam.",
        link: "Link",
        pin: "Kod startowy",
        kopiuj: "Kopiuj",
        skopiowano: "Skopiowano",
        bladKopiowania: "Nie udało się skopiować. Zaznacz pole i skopiuj ręcznie.",
        zamknij: "Zamknij",
        zamknijBezKopiowania: "Nie skopiowano kodu. Po zamknięciu okna nie zobaczysz go już. Zamknąć mimo to?",
        nowyPinTytul: "Nowy kod startowy",
        nowyPinOpis: "Stary PIN przestał działać, urządzenia zostały wylogowane. Kod widzisz tylko teraz, działa raz i przez 7 dni.",
      },
      historia: {
        tytul: "Historia logowań",
        brak: "Jeszcze nic się nie wydarzyło.",
        kolumny: { kiedy: "Kiedy", co: "Zdarzenie", kto: "Link" },
        zdarzenia: {
          "klient.logowanie_ok": "Udane logowanie",
          "klient.logowanie_blad": "Nieudana próba logowania",
          "klient.blokada_24h": "Blokada linku na 24 godziny (10 nieudanych prób)",
          "klient.link_zamrozony": "Zamrożenie linku (druga blokada w ciągu 30 dni)",
          "klient.kod_startowy_ok": "Wpisano kod startowy",
          "klient.pin_ustawiony": "Klient ustawił własny PIN",
          "klient.pin_zmieniony": "Klient zmienił PIN",
          "klient.zmiana_pinu_blad": "Nieudana próba zmiany PIN-u",
          "klient.wylogowanie": "Wylogowanie",
          "klient.plik_pobrany": "Pobranie pliku",
          "link.utworzony": "Utworzono link",
          "link.wygaszony": "Wygaszono link",
          "link.pin_zresetowany": "Wydano nowy kod startowy",
          "link.urzadzenia_wylogowane": "Wylogowano wszystkie urządzenia",
          "link.skopiowany": "Skopiowano dostęp",
          "link.odszyfrowany": "Pokazano link (odszyfrowano token)",
        },
      },
      bledy: {
        klientDemo: "Klient demonstracyjny nie dostaje linków dostępu.",
        klientZakonczony: "Współpraca z tym klientem jest zakończona. Wznów ją w zakładce Dane i współpraca, zanim utworzysz link.",
        brakEtykiety: "Wpisz opis linku albo wybierz osobę kontaktową.",
        ogolny: "Nie udało się wykonać tej operacji. Odśwież stronę i spróbuj ponownie.",
      },
    },
    /** Zakładka Raporty (SPEC rozdz. 9): wklejony link albo webhook z Zapiera. */
    raporty: {
      tytul: "Raporty",
      opis: "Link do raportu z systemu raportów (raporty.foodiemedia.pl), jeden na miesiąc. Ręcznie albo webhookiem z Zapiera.",
      brak: "Ten klient nie ma jeszcze raportów.",
      kolumny: { okres: "Miesiąc", lokal: "Lokal", tytul: "Tytuł", zrodlo: "Źródło", opublikowano: "Dodano" },
      zrodlo: { reczne: "ręcznie", webhook: "webhook" },
      otworz: "Otwórz",
      usun: "Usuń",
      usunPotwierdz: "Usunąć ten raport? Klient przestanie go widzieć.",
      dodaj: "Dodaj raport",
      dialog: {
        tytul: "Dodaj raport",
        opis: "Wklej link z systemu raportów. Ten sam miesiąc i lokal nadpisze poprzedni link.",
        link: "Link do raportu",
        linkPodpowiedz: "https://raporty.foodiemedia.pl/r/...",
        miesiac: "Miesiąc raportu",
        lokal: "Lokal",
        tytulPola: "Tytuł (opcjonalnie)",
        miesiacWspolpracy: "Numer miesiąca współpracy (opcjonalnie)",
        zapisz: "Dodaj raport",
        zapisywanie: "Zapisujemy...",
        anuluj: "Anuluj",
        nadpisano: "Zaktualizowano link raportu za ten miesiąc.",
        dodano: "Raport dodany. Klient widzi go w zakładce Raporty.",
      },
      bledy: {
        link: "Wklej link zaczynający się od https://raporty.foodiemedia.pl/.",
        miesiac: "Wybierz miesiąc raportu.",
        lokal: "Wybierz lokal. Ten klient ma osobny raport dla każdej restauracji.",
        miesiacWspolpracy: "Numer miesiąca współpracy to liczba od 1 wzwyż.",
        ogolny: "Nie udało się zapisać raportu. Odśwież stronę i spróbuj ponownie.",
      },
    },
    /** Zakładka Faktury (SPEC rozdz. 10): wystawione w Fakturowo, wpisane ręcznie; po_terminie przestawia cron. */
    faktury: {
      tytul: "Faktury",
      opis: "Faktury z Fakturowo wpisujesz ręcznie. Status „po terminie\" ustawia się sam codziennie rano; ręcznie oznaczasz tylko opłacenie.",
      brak: "Ten klient nie ma jeszcze faktur.",
      demo: "Klient demonstracyjny nie dostaje faktur.",
      kolumny: { numer: "Numer", wystawiono: "Wystawiono", termin: "Termin", netto: "Netto", brutto: "Brutto", status: "Status", pdf: "PDF", akcje: "Akcje" },
      status: { do_zaplaty: "Do zapłaty", po_terminie: "Po terminie", oplacona: "Opłacona" },
      poTerminie: "{n} dni po terminie",
      pdfPobierz: "Pobierz",
      pdfBrak: "brak",
      pdfDodaj: "Dodaj PDF",
      pdfPodmien: "Podmień PDF",
      oznaczOplacona: "Oznacz jako opłaconą",
      cofnijOplacenie: "Cofnij opłacenie",
      cofnijPotwierdz: "Cofnąć oznaczenie jako opłacona? Status wróci do „do zapłaty\" albo „po terminie\" zależnie od terminu.",
      usun: "Usuń",
      usunPotwierdz: "Usunąć fakturę {numer}? Klient przestanie ją widzieć. PDF zostanie w magazynie.",
      dodaj: "Dodaj fakturę",
      dialog: {
        tytul: "Dodaj fakturę",
        opis: "Przepisz dane z Fakturowo. Kwotę brutto podpowiadamy przy stawce 23%, możesz ją poprawić.",
        numer: "Numer faktury",
        numerPodpowiedz: "np. FV/2026/09/031",
        wystawiono: "Data wystawienia",
        termin: "Termin płatności",
        netto: "Kwota netto (zł)",
        brutto: "Kwota brutto (zł)",
        notatka: "Notatka wewnętrzna (opcjonalnie)",
        notatkaOpis: "Klient jej nie widzi.",
        pdf: "PDF faktury (opcjonalnie)",
        zapisz: "Dodaj fakturę",
        zapisywanie: "Zapisujemy...",
        anuluj: "Anuluj",
        dodano: "Faktura dodana. Klient widzi ją w zakładce Faktury i dokumenty.",
      },
      dialogOplacenia: {
        tytul: "Oznacz jako opłaconą",
        data: "Data wpłaty",
        zapisz: "Zapisz",
        anuluj: "Anuluj",
      },
      dialogPdf: {
        tytul: "PDF faktury {numer}",
        opis: "Nowy plik zastąpi poprzedni w panelu klienta.",
        zapisz: "Zapisz PDF",
        anuluj: "Anuluj",
      },
      bledy: {
        numer: "Wpisz numer faktury.",
        numerZajety: "Faktura z tym numerem już jest na liście tego klienta.",
        daty: "Sprawdź daty: termin płatności nie może być wcześniejszy niż data wystawienia.",
        kwoty: "Wpisz kwoty netto i brutto większe od zera, brutto nie mniejsze niż netto.",
        dataWplaty: "Wpisz datę wpłaty.",
        klientDemo: "Klient demonstracyjny nie dostaje faktur.",
        plik: "Nie udało się przypiąć pliku. Wyślij go jeszcze raz.",
        ogolny: "Nie udało się zapisać faktury. Odśwież stronę i spróbuj ponownie.",
      },
    },
    /** Zakładka Dokumenty (SPEC rozdz. 10, 17): umowa, aneksy, umowa powierzenia. Tylko admin i csm. */
    dokumenty: {
      tytul: "Dokumenty",
      opis: "Umowa, aneksy i umowa powierzenia przetwarzania danych. Klient pobiera je w zakładce Faktury i dokumenty.",
      brak: "Ten klient nie ma jeszcze dokumentów.",
      kolumny: { rodzaj: "Rodzaj", tytul: "Tytuł", obowiazujeOd: "Obowiązuje od", dodano: "Dodano", plik: "Plik" },
      rodzaje: { umowa: "Umowa", aneks: "Aneks", powierzenie: "Umowa powierzenia", inne: "Inny dokument" },
      pobierz: "Pobierz",
      usun: "Usuń",
      usunPotwierdz: "Usunąć dokument „{tytul}\"? Klient przestanie go widzieć.",
      dodaj: "Dodaj dokument",
      dialog: {
        tytul: "Dodaj dokument",
        rodzaj: "Rodzaj dokumentu",
        tytulPola: "Tytuł",
        tytulPodpowiedz: "np. Umowa o współpracy z 1 kwietnia 2026",
        obowiazujeOd: "Obowiązuje od (opcjonalnie)",
        pdf: "PDF dokumentu",
        zapisz: "Dodaj dokument",
        zapisywanie: "Zapisujemy...",
        anuluj: "Anuluj",
        dodano: "Dokument dodany. Klient widzi go w zakładce Faktury i dokumenty.",
      },
      bledy: {
        tytul: "Wpisz tytuł dokumentu.",
        plik: "Wybierz plik PDF i poczekaj, aż się wyśle.",
        ogolny: "Nie udało się zapisać dokumentu. Odśwież stronę i spróbuj ponownie.",
      },
    },
    /** Upload PDF (faktury, dokumenty): ta sama droga co materiały, tylko PDF do 25 MB. */
    pdf: {
      wybierz: "Wybierz plik PDF",
      formaty: "Tylko PDF, do 25 MB.",
      wysylanie: "Wysyłamy plik... {procent}%",
      sprawdzanie: "Sprawdzamy plik...",
      gotowy: "Plik gotowy: {nazwa}",
      bledy: {
        nieobslugiwany: "To nie jest plik PDF. Zapisz dokument jako PDF i wyślij ponownie.",
        zaDuzy: "Plik jest za duży. Limit: {limit}.",
        pozwolenie: "Pozwolenie na wysyłkę wygasło. Wybierz plik jeszcze raz.",
        brakPliku: "Plik nie dotarł do magazynu. Sprawdź połączenie i spróbuj ponownie.",
        wysylka: "Wysyłka pliku się nie powiodła. Sprawdź połączenie i spróbuj ponownie.",
      },
    },
    /** Ustawienia -> Powiadomienia (SPEC rozdz. 15): kolejka outbox do Zapiera, tylko admin. */
    powiadomienia: {
      tytul: "Powiadomienia",
      opis: "Zdarzenia z panelu wysyłane do Zapiera (jeden webhook, Zapier kieruje je na Slacka). Cron sprawdza kolejkę co minutę, po pięciu nieudanych próbach zdarzenie dostaje status „nieudane\".",
      adresSkonfigurowany: "Adres webhooka Zapiera jest skonfigurowany.",
      adresBrak: "Brak adresu webhooka (ZAPIER_WEBHOOK_URL). Zdarzenia czekają w kolejce i wyślą się po ustawieniu zmiennej w Vercelu.",
      brak: "Kolejka jest pusta.",
      kolumny: { zdarzenie: "Zdarzenie", klient: "Klient", status: "Status", proby: "Próby", blad: "Ostatni błąd", nastepna: "Następna próba", utworzono: "Utworzono" },
      status: { pending: "czeka", sent: "wysłane", failed: "nieudane" },
      ponow: "Ponów",
      ponowiono: "Zdarzenie wróciło do kolejki.",
      podsumowanie: "Ostatnie {n} zdarzeń.",
    },
    /** Monitoring cronów (tylko admin, pulpit). */
    crony: {
      tytul: "Automaty panelu wymagają uwagi",
      nazwy: { "auto-akceptacja": "Auto-akceptacja (co godzinę)", outbox: "Powiadomienia na Slacka (co minutę)", faktury: "Statusy faktur (codziennie)", retencja: "Retencja (co miesiąc)" },
      brak: "{cron}: brak zapisu przebiegu. Sprawdź crony w Vercelu (plan Pro, zmienna CRON_SECRET).",
      opozniony: "{cron}: ostatni przebieg {kiedy}. Sprawdź logi funkcji w Vercelu.",
      bledy: "{cron}: ostatni przebieg zakończył się z błędami ({n}). Sprawdź logi funkcji w Vercelu.",
      nieudane: "Powiadomienia: {n} zdarzeń nie doszło do Zapiera. Ponów je w Ustawieniach.",
      zobacz: "Otwórz powiadomienia",
    },
    nowyKlient: {
      tytul: "Nowy klient",
      opis: "Dane z umowy. Wszystko poprawisz później w zakładce „Dane i współpraca\" na karcie klienta.",
      przycisk: "Nowy klient",
      dane: {
        naglowek: "Dane klienta",
        nazwa: "Nazwa klienta",
        nazwaPodpowiedz: "np. Nova Sushi",
        slug: "Adres w panelu (slug)",
        slugOpis: "Małe litery, cyfry i myślniki. Widoczny w adresach panelu zespołu.",
        kategoria: "Kategoria",
        pakiet: "Pakiet",
        kwota: "Kwota netto miesięcznie (zł)",
        slack: "Kanał Slack",
        slackPodpowiedz: "np. #nova-sushi",
        startWspolpracy: "Współpraca od",
        opiekun: "Opiekun klienta",
        bezOpiekuna: "bez opiekuna (uzupełnij później)",
        przypisani: "Zespół klienta",
        przypisaniOpis: "Content creator i media buyer widzą klienta dopiero po przypisaniu.",
      },
      lokale: {
        naglowek: "Lokale",
        opis: "Kategoria 1: każdy lokal ma osobne materiały i osobny pakiet. Kategorie 2 i 3: jeden komplet materiałów, reklamy per lokal.",
        nazwa: "Nazwa lokalu",
        miasto: "Miasto",
        fb: "Nazwa strony na Facebooku",
        ig: "Nick na Instagramie",
        igPodpowiedz: "bez @ (puste = placementy IG wyszarzone)",
        dodaj: "Dodaj lokal",
        usun: "Usuń lokal",
      },
      kontakty: {
        naglowek: "Osoby kontaktowe",
        opis: "Każda osoba dostanie potem własny link i PIN w zakładce Dostęp. Pierwsza osoba jest główna.",
        imie: "Imię i nazwisko",
        rola: "Rola",
        rolaPodpowiedz: "np. właściciel, manager",
        telefon: "Telefon",
        email: "E-mail",
        dodaj: "Dodaj osobę",
        usun: "Usuń osobę",
      },
      utworz: "Utwórz klienta",
      tworzenie: "Tworzymy...",
      bledy: {
        nazwa: "Wpisz nazwę klienta.",
        slug: "Slug może mieć tylko małe litery, cyfry i myślniki (2 do 60 znaków).",
        slugZajety: "Klient z takim slugiem już istnieje. Zmień slug.",
        kwota: "Kwota netto musi być liczbą nie mniejszą od zera.",
        lokal: "Każdy lokal potrzebuje nazwy i nazwy strony na Facebooku.",
        kontakt: "Każda osoba kontaktowa potrzebuje imienia i nazwiska.",
        email: "Adres e-mail osoby kontaktowej wygląda na niepoprawny.",
        data: "Data startu współpracy ma zły format.",
        godzinyAuto: "Termin automatycznej akceptacji: od 72 do 720 godzin albo puste pole (72 h jak dla wszystkich).",
        godzinyPublikacji: "Godziny publikacji: od 1 do 6 pełnych godzin 0-23, oddzielonych przecinkami, np. 12, 18.",
        ogolny: "Nie udało się utworzyć klienta. Spróbuj ponownie.",
      },
    },
    retencja: {
      tytul: "Retencja materiałów",
      opis: "Pakiety, których okres skończył się ponad {n} miesięcy temu. Cron zgłasza je pierwszego dnia miesiąca, ale nic nie kasuje się samo: decyzję podejmujesz tutaj. Usunięcie kasuje materiały, pliki, komentarze i historię pakietu; faktury, dokumenty i raporty zostają.",
      sprzatanie: "Ten sam cron kasuje wygasłe sesje klientów po 90 dniach i wpisy audytu starsze niż 12 miesięcy.",
      brak: "Nic nie czeka na decyzję.",
      kolumny: { klient: "Klient", pakiet: "Pakiet", pliki: "Pliki", zgloszono: "Zgłoszono", akcja: "Decyzja" },
      usun: "Usuń materiały",
      usunPotwierdz: "Usunąć materiały pakietu „{pakiet}\" klienta {klient}? Znikną pliki, komentarze i historia pakietu. Tego nie da się cofnąć.",
      zachowaj: "Zachowaj 12 miesięcy",
      sprawdzTeraz: "Sprawdź teraz",
      sprawdzanie: "Sprawdzamy...",
      sprawdzono: "Sprawdzono {sprawdzone} pakietów, nowych zgłoszeń: {nowe}.",
      historia: "Ostatnie decyzje",
      brakHistorii: "Jeszcze żadnej decyzji.",
      decyzja: { zachowaj: "zachowano do {data}", usun: "usunięto {data}" },
      przez: "{osoba}, {data}",
      pakietUsuniety: "pakiet usunięty",
      bledy: { ogolny: "Nie udało się zapisać decyzji. Odśwież stronę i spróbuj ponownie." },
    },
    /** Zakładka „Dane i współpraca" karty klienta (plan domknięcia, Etap 1): admin i csm. */
    daneKlienta: {
      zapisz: "Zapisz",
      zapisywanie: "Zapisujemy...",
      zapisano: "Zapisano.",
      anuluj: "Anuluj",
      edytuj: "Zmień",
      dane: {
        tytul: "Dane klienta",
        opis: "Nazwa, pakiet i kwota z umowy. Adres klienta w panelu (slug) się nie zmienia, bo trafia do powiadomień na Slacku.",
        kategoriaZablokowana: "Kategorii nie da się zmienić, bo klient ma już pakiety albo raporty.",
      },
      lokale: {
        tytul: "Lokale",
        opis: "Nazwa strony na Facebooku i nick na Instagramie trafiają do podglądów 1:1. Bez nicku placementy Instagrama są wyszarzone.",
        adres: "Adres",
        dodaj: "Dodaj lokal",
        nowy: "Nowy lokal",
        brakIg: "bez Instagrama",
        zmianaNazwyKat1: "Klient ma raporty per lokal: po zmianie nazwy lokalu popraw ją też w formularzu raportów w Zapierze.",
        zdjecie: "Zdjęcie profilowe strony",
        zdjecieOpis: "Widoczne tylko w ramce podglądu, jak na Facebooku. JPG, PNG albo WEBP do 5 MB.",
        zdjecieWybierz: "Wgraj zdjęcie",
        zdjecieZmien: "Zmień zdjęcie",
        zdjecieWysylanie: "Wysyłamy zdjęcie...",
        zdjecieBrak: "brak zdjęcia",
        zdjecieBledy: {
          nieobslugiwany: "To nie jest JPG, PNG ani WEBP. Zapisz zdjęcie w jednym z tych formatów i spróbuj ponownie.",
          zaDuzy: "Zdjęcie jest za duże. Limit: {limit}.",
          wysylka: "Wysyłka zdjęcia się nie powiodła. Sprawdź połączenie i spróbuj ponownie.",
          ogolny: "Nie udało się zapisać zdjęcia. Spróbuj z innym plikiem.",
        },
      },
      kontakty: {
        tytul: "Osoby kontaktowe",
        opis: "Każda osoba dostaje własny link w zakładce Dostęp. Telefon i e-mail widzi tylko zespół.",
        dodaj: "Dodaj osobę",
        nowa: "Nowa osoba",
        glowna: "główna",
        ustawGlowna: "Ustaw jako główną",
        linki: "Aktywne linki: {n}",
        archiwizuj: "Zakończ współpracę z osobą",
        archiwizujTytul: "Zakończyć współpracę z {osoba}?",
        archiwizujOpis: "Osoba zniknie z wyboru przy nowym linku, a jej telefon i e-mail zostaną usunięte. Imię zostaje w historii akceptacji.",
        wygasLinki: "Wygaś też jej linki dostępu i wyloguj urządzenia ({n})",
        archiwizujPotwierdz: "Zakończ współpracę z osobą",
        zarchiwizowane: "Byłe osoby kontaktowe",
      },
      zespol: {
        tytul: "Zespół klienta",
        opis: "Opiekuna klient widzi w „Twój pakiet\". Content creator i media buyer widzą klienta w panelu dopiero po przypisaniu.",
        opiekun: "Opiekun",
        bezOpiekuna: "bez opiekuna",
        przypisani: "Przypisane osoby",
        straconyDostep: "Oddałeś opiekę nad tym klientem i nie masz już do niego dostępu.",
      },
      akceptacja: {
        tytul: "Akceptacja i publikacja",
        opis: "Regulamin pozwala termin automatycznej akceptacji tylko wydłużyć: 72 godziny to minimum.",
        auto: "Automatyczna akceptacja po terminie (domyślnie dla nowych pakietów)",
        godziny: "Termin automatycznej akceptacji w godzinach",
        godzinyPodpowiedz: "puste = 72 h jak dla wszystkich",
        publikacja: "Domyślne godziny publikacji",
        publikacjaPodpowiedz: "np. 12, 18",
      },
      bledy: {
        ogolny: "Nie udało się zapisać. Odśwież stronę i spróbuj ponownie.",
        opiekun: "Opiekunem może być tylko aktywny admin albo opiekun klienta.",
      },
    },
    pierwszeKroki: {
      tytul: "Pierwsze kroki",
      opis: "Znika, gdy wszystko jest gotowe.",
      linki: "Link i PIN dla każdej osoby kontaktowej",
      zdjecia: "Zdjęcia profilowe lokali do podglądów",
      zespol: "Przypisany content creator",
      dokumenty: "Umowa i umowa powierzenia w Dokumentach",
      pakiet: "Pierwszy pakiet materiałów",
    },
    ustawieniaKlienta: {
      tytul: "Współpraca",
      opis: "Zakończenie współpracy wygasza wszystkie linki dostępu, wylogowuje urządzenia klienta i zdejmuje klienta z pulpitu. Dane zostają do czasu osobnej decyzji o ich usunięciu.",
      aktywneLinki: "Aktywne linki: {n}",
      zakoncz: "Zakończ współpracę",
      zakonczPotwierdz: "Zakończyć współpracę z {klient}? Wszystkie linki dostępu wygasną, klient zostanie wylogowany ze wszystkich urządzeń, a pakiety czekające na akceptację wrócą do szkicu.",
      zakonczono: "Współpraca zakończona {data}. Linki dostępu są wygaszone.",
      wznow: "Wznów współpracę",
      wznowOpis: "Wznowienie przywraca klienta na pulpit. Stare linki nie wracają: utwórz nowe w zakładce Dostęp.",
      przerwa: "Przerwa we współpracy",
      przerwaPotwierdz: "Zrobić przerwę we współpracy z {klient}? Klient zniknie z pulpitu, pakiety czekające na akceptację wrócą do szkicu, a automatyczna akceptacja się zatrzyma. Linki klienta dalej działają.",
      przerwaTrwa: "Przerwa we współpracy. Linki klienta działają, nowych materiałów nie wysyłamy.",
      wznowOpisPrzerwa: "Wznowienie przywraca klienta na pulpit. Linki działały przez całą przerwę.",
      usuwanie: {
        tytul: "Usuń dane klienta",
        opis: "Kasuje wszystko: lokale, osoby kontaktowe, linki, pakiety z materiałami i plikami, komentarze, faktury, dokumenty i raporty. Wpisy audytu zostają na 12 miesięcy. Tego nie da się cofnąć.",
        najpierwZakoncz: "Najpierw zakończ współpracę. Usunięcie danych jest możliwe tylko dla zakończonej współpracy.",
        tylkoAdmin: "Usunąć dane klienta może wyłącznie admin.",
        klientDemo: "Klienta demonstracyjnego nie usuwamy: potrzebuje go rola sprzedaży.",
        przepisz: "Przepisz nazwę klienta, żeby odblokować przycisk:",
        podpowiedz: "nazwa klienta",
        przycisk: "Usuń dane klienta bezpowrotnie",
        usuwanie: "Usuwamy...",
        usunieto: "Dane klienta {klient} zostały usunięte.",
        bledy: { nazwa: "Nazwa się nie zgadza. Przepisz ją dokładnie tak, jak w nagłówku karty.", ogolny: "Nie udało się usunąć danych. Spróbuj ponownie albo sprawdź logi." },
      },
      bledy: { ogolny: "Nie udało się zapisać zmiany. Odśwież stronę i spróbuj ponownie." },
    },
    ustawienia: {
      tytul: "Ustawienia",
      zespol: {
        tytul: "Zespół",
        opis: "Tylko osoby z tej listy mogą zalogować się do panelu zespołu. Dodanie osoby tworzy jej konto; kod logowania dostaje na e-mail przy pierwszym wejściu.",
        dodaj: "Dodaj osobę",
        imie: "Imię",
        email: "Adres e-mail",
        rola: "Rola",
        dodawanie: "Dodajemy...",
        kolumny: { osoba: "Osoba", email: "E-mail", rola: "Rola", status: "Status" },
        aktywny: "Aktywny",
        nieaktywny: "Nieaktywny",
        dezaktywuj: "Dezaktywuj",
        klienci: "Klienci: {n}",
        klienciOpis: "opiekun {o}, przypisany {p}",
        dezaktywujOpiekuna: "{osoba} jest opiekunem {n} klientów. Po dezaktywacji zmień opiekuna na kartach tych klientów. Dezaktywować?",
        aktywuj: "Aktywuj",
        kontakt: "Kontakt dla klienta",
        kontaktOpis: "Co klient widzi w „Twój pakiet\" przy imieniu opiekuna, np. służbowy WhatsApp albo e-mail. Bez numerów prywatnych. Puste = ogólny kontakt agencji.",
        kontaktPodpowiedz: "np. WhatsApp +48 500 000 000",
        kontaktZapisz: "Zapisz",
        kontaktZapisano: "Zapisano.",
        bledy: {
          dane: "Uzupełnij imię, poprawny adres e-mail i rolę.",
          istnieje: "Osoba z tym adresem już jest na liście.",
          ogolny: "Nie udało się dodać osoby. Spróbuj ponownie.",
          allowlista: "Ten adres nie przechodzi filtra domen (TEAM_EMAIL_ALLOWLIST). Dopisz domenę albo adres do zmiennej środowiskowej.",
        },
      },
    },
  },
  regulamin: {
    tytul: "Regulamin panelu klienta Foodie Media",
    obowiazujeOd: "Obowiązuje od 3 września 2026",
    sekcje: [
      {
        naglowek: "§ 1. Kto prowadzi panel",
        tresc: [
          {
            punkty: [
              "Panel dostępny pod adresem panel.foodiemedia.pl prowadzi **Foodie Media Sp. z o.o.** z siedzibą w Łodzi, ul. Henryka Sienkiewicza 85/87 lok. 8, 90-057 Łódź, NIP 7252349929, REGON 540281469, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego pod numerem KRS 0001140926, dalej: **Agencja**.",
              "Kontakt w sprawach panelu: kontakt@foodiemedia.pl.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 2. Co znaczą używane pojęcia",
        tresc: [
          {
            punkty: [
              "**Klient** - przedsiębiorca, z którym Agencja zawarła umowę o świadczenie usług marketingowych.",
              "**Panel** - narzędzie internetowe, w którym Klient przegląda i akceptuje materiały, ogląda harmonogram publikacji, raporty, faktury i dokumenty.",
              "**Osoba upoważniona** - osoba wskazana przez Klienta, która otrzymuje dostęp do Panelu i działa w imieniu Klienta.",
              "**Materiały** - posty, relacje, filmy i kreacje reklamowe wraz z tekstami, przygotowane przez Agencję w ramach umowy.",
              "**Pakiet** - zestaw Materiałów przygotowany na dany miesiąc współpracy, obejmujący treści organiczne i kampanie reklamowe.",
              "**Akceptacja** - zgoda Klienta na publikację Materiałów w kształcie przedstawionym w Panelu.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 3. Do czego służy Panel",
        tresc: [
          {
            punkty: [
              "Panel jest narzędziem roboczym w ramach umowy między Agencją a Klientem. Nie jest odrębną usługą i nie podlega odrębnej opłacie.",
              "Panel służy do: przeglądania i akceptacji Materiałów, zgłaszania uwag, podglądu harmonogramu publikacji, dostępu do raportów miesięcznych, faktur i dokumentów oraz zapoznania się z dodatkowymi usługami Agencji.",
              "Panel nie służy do zawierania umów ani do dokonywania płatności.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 4. Dostęp i bezpieczeństwo",
        tresc: [
          {
            punkty: [
              "Dostęp do Panelu odbywa się przez indywidualny link oraz PIN. Opiekun Klienta przekazuje Osobie upoważnionej link i jednorazowy kod startowy ważny 7 dni; przy pierwszym wejściu Osoba upoważniona ustawia własny PIN (od 4 do 6 cyfr) i może go później zmienić w Panelu.",
              "Link wraz z PIN-em stanowią dane dostępowe. Klient odpowiada za to, komu je przekazuje, i zobowiązuje się nie udostępniać ich osobom nieuprawnionym.",
              "Agencja nie przechowuje PIN-u w postaci, z której da się go odczytać, i nie zna PIN-u ustawionego przez Osobę upoważnioną. Po kilku nieudanych próbach dostęp jest czasowo blokowany, a po powtarzających się próbach wstrzymywany do czasu wydania nowego kodu startowego.",
              "Klient niezwłocznie informuje Agencję o utracie kontroli nad danymi dostępowymi lub o podejrzeniu dostępu osoby nieuprawnionej. Agencja wygasza wtedy dane dostępowe albo wydaje nowy kod startowy.",
              "Klient może w każdej chwili poprosić o dodanie lub odebranie dostępu konkretnej Osobie upoważnionej.",
              "Agencja odnotowuje w systemie datę i godzinę logowań, akceptacji i zgłoszonych uwag. Zapisy te służą ustaleniu przebiegu współpracy.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 5. Akceptacja Materiałów",
        tresc: [
          {
            punkty: [
              "Agencja udostępnia Pakiet w Panelu i informuje o tym Klienta ustalonym kanałem kontaktu.",
              "Klient akceptuje Pakiet w całości albo zgłasza uwagi do poszczególnych Materiałów.",
              "Klient zgłasza uwagi w terminie 72 godzin od udostępnienia Pakietu w Panelu.",
              "Brak zgłoszenia uwag w tym terminie oznacza akceptację Pakietu i uprawnia Agencję do rozpoczęcia publikacji zgodnie z harmonogramem.",
              "Panel informuje o upływającym terminie w sposób widoczny od chwili udostępnienia Pakietu, w tym o pozostałym czasie i o skutku bezczynności.",
              "Zgłoszenie uwag wstrzymuje bieg terminu. Termin biegnie od nowa od chwili udostępnienia poprawionej wersji Pakietu.",
              "Opiekun Klienta może wydłużyć termin lub wyłączyć automatyczną akceptację dla konkretnego Pakietu, na wniosek Klienta złożony przed jego upływem.",
              "Liczba rund poprawek nie jest ograniczona. Agencja może jednak wskazać, że kolejne poprawki wykraczają poza zakres umowy - wtedy ustala z Klientem odrębne warunki.",
              "Po akceptacji Klient nadal może zgłaszać uwagi. Agencja rozpatruje je i informuje, czy i kiedy jest w stanie je uwzględnić, przy czym Materiały już opublikowane nie podlegają wycofaniu.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 6. Harmonogram publikacji",
        tresc: [
          {
            punkty: [
              "Daty publikacji Materiałów Agencja przedstawia w Panelu. Klient widzi je przy każdym Materiale i w widoku kalendarza.",
              "Harmonogram ma charakter planu. Agencja może przesunąć publikację z przyczyn technicznych lub z powodu ograniczeń platform, informując o tym Klienta.",
              "Kampanie reklamowe nie mają wskazanej daty publikacji - Agencja uruchamia je po akceptacji, w ramach uzgodnionego okresu rozliczeniowego.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 7. Raporty, faktury i dokumenty",
        tresc: [
          {
            punkty: [
              "Raport miesięczny Agencja udostępnia w Panelu jako odnośnik do dokumentu pod indywidualnym adresem.",
              "Faktury w Panelu mają charakter informacyjny. Dokumentem księgowym jest faktura wystawiona i doręczona zgodnie z umową.",
              "Statusy płatności w Panelu Agencja aktualizuje na podstawie własnych zapisów. Rozbieżność Klient zgłasza opiekunowi.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 8. Dostępność Panelu",
        tresc: [
          {
            punkty: [
              "Agencja dokłada starań, aby Panel działał bez przerw, ale nie gwarantuje ciągłej dostępności.",
              "Agencja może wprowadzać przerwy techniczne. O przerwach planowanych informuje z wyprzedzeniem.",
              "Niedostępność Panelu nie wstrzymuje biegu terminu z § 5 ust. 3, jeżeli trwała krócej niż 6 godzin. Przy dłuższej niedostępności termin ulega przedłużeniu o czas jej trwania.",
              "Do korzystania z Panelu potrzebne jest urządzenie z dostępem do internetu i aktualna przeglądarka internetowa.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 9. Prawa do Materiałów",
        tresc: [
          {
            punkty: [
              "Zasady przeniesienia praw do Materiałów oraz zakres licencji określa umowa między Agencją a Klientem. Panel nie zmienia tych zasad.",
              "Klient nie udostępnia Materiałów osobom trzecim przed publikacją, poza Osobami upoważnionymi.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 10. Reklamacje",
        tresc: [
          {
            punkty: [
              "Uwagi dotyczące działania Panelu Klient zgłasza na adres kontakt@foodiemedia.pl.",
              "Agencja odpowiada w terminie 14 dni od otrzymania zgłoszenia.",
              "Zgłoszenia dotyczące treści Materiałów Klient kieruje przez Panel albo do opiekuna.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 11. Zmiany regulaminu",
        tresc: [
          {
            punkty: [
              "Agencja może zmienić regulamin z ważnych przyczyn, w szczególności przy zmianie zakresu funkcji Panelu lub przepisów prawa.",
              "O zmianie Agencja informuje Klienta z co najmniej 14-dniowym wyprzedzeniem, przez Panel lub ustalonym kanałem kontaktu.",
              "Zmiana § 5 wymaga odrębnej zgody Klienta i nie wchodzi w życie w trybie z ust. 2.",
            ],
          },
        ],
      },
      {
        naglowek: "§ 12. Postanowienia końcowe",
        tresc: [
          {
            punkty: [
              "W sprawach nieuregulowanych stosuje się umowę między Agencją a Klientem, a w dalszej kolejności przepisy prawa polskiego.",
              "Regulamin stanowi uzupełnienie umowy. W razie sprzeczności pierwszeństwo ma umowa.",
              "Zasady przetwarzania danych osobowych opisuje Polityka prywatności panelu.",
            ],
          },
        ],
      },
    ],
  },
  prywatnosc: {
    tytul: "Polityka prywatności panelu klienta",
    obowiazujeOd: "Obowiązuje od 3 września 2026",
    sekcje: [
      {
        naglowek: "1. Kto odpowiada za Twoje dane",
        tresc: [
          "Administratorem danych osobowych jest **Foodie Media Sp. z o.o.** z siedzibą w Łodzi, ul. Henryka Sienkiewicza 85/87 lok. 8, 90-057 Łódź, NIP 7252349929, REGON 540281469, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego pod numerem KRS 0001140926.",
          "W sprawach dotyczących danych osobowych napisz na kontakt@foodiemedia.pl.",
          "Nie wyznaczyliśmy inspektora ochrony danych - wszystkie sprawy prowadzimy pod tym adresem.",
        ],
      },
      {
        naglowek: "2. Jakie dane przetwarzamy",
        tresc: [
          { podtytul: "Dane osób, które korzystają z panelu:" },
          { lista: ["imię i nazwisko,", "rola w firmie (np. właściciel, manager),", "numer telefonu,", "adres e-mail, jeśli został podany."] },
          { podtytul: "Dane, które powstają w trakcie korzystania z panelu:" },
          {
            lista: [
              "data i godzina logowania oraz nieudanych prób logowania,",
              "data i godzina otwarcia materiałów, akceptacji i zgłoszonych uwag,",
              "treść uwag zgłoszonych w panelu,",
              "skrócony, nieodwracalnie przekształcony zapis adresu IP i informacji o przeglądarce.",
            ],
          },
          "**Czego nie zbieramy:** nie zbieramy w panelu danych gości restauracji, nie prowadzimy analityki zewnętrznej, nie stosujemy cookies marketingowych ani śledzących.",
        ],
      },
      {
        naglowek: "3. Po co i na jakiej podstawie",
        tresc: [
          {
            tabela: {
              naglowki: ["Cel", "Podstawa prawna"],
              wiersze: [
                ["Udostępnienie panelu i realizacja umowy o usługi marketingowe", "art. 6 ust. 1 lit. b RODO - niezbędność do wykonania umowy; wobec osób działających w imieniu klienta: art. 6 ust. 1 lit. f - nasz uzasadniony interes w kontakcie z klientem"],
                ["Ustalenie, kto i kiedy zaakceptował materiały", "art. 6 ust. 1 lit. f - uzasadniony interes: udokumentowanie przebiegu współpracy"],
                ["Zabezpieczenie panelu przed nieuprawnionym dostępem (logi, ograniczanie prób logowania)", "art. 6 ust. 1 lit. f - uzasadniony interes: bezpieczeństwo danych"],
                ["Wystawianie i przechowywanie faktur", "art. 6 ust. 1 lit. c - obowiązek prawny wynikający z przepisów podatkowych i o rachunkowości"],
                ["Rozpatrywanie reklamacji i obrona przed roszczeniami", "art. 6 ust. 1 lit. f - uzasadniony interes"],
              ],
            },
          },
        ],
      },
      {
        naglowek: "4. Komu powierzamy dane",
        tresc: [
          "Korzystamy z dostawców, którzy przetwarzają dane na nasze zlecenie:",
          {
            lista: [
              "**Supabase** - baza danych i przechowywanie plików; serwery w regionie Europy (Frankfurt, Niemcy),",
              "**Vercel** - hosting aplikacji; funkcje uruchamiane w regionie Frankfurt,",
              "**Resend** - wysyłka wiadomości z kodami logowania,",
              "**Google** - przechowywanie plików źródłowych materiałów na Dysku Google,",
              "**Zapier** - przekazywanie powiadomień o zdarzeniach w panelu do naszego komunikatora wewnętrznego,",
              "**Slack** - komunikacja wewnętrzna zespołu obsługującego klienta.",
            ],
          },
          "Supabase, Vercel i Resend są spółkami z siedzibą w Stanach Zjednoczonych, mimo że dane przechowujemy w Unii Europejskiej. Przekazanie danych poza Europejski Obszar Gospodarczy może więc wystąpić w zakresie obsługi technicznej. Odbywa się ono na podstawie standardowych klauzul umownych zatwierdzonych przez Komisję Europejską.",
          "Danych nie sprzedajemy i nie udostępniamy do celów marketingowych podmiotom trzecim.",
        ],
      },
      {
        naglowek: "5. Jak długo trzymamy dane",
        tresc: [
          {
            tabela: {
              naglowki: ["Rodzaj danych", "Okres"],
              wiersze: [
                ["Materiały i historia akceptacji", "24 miesiące od udostępnienia"],
                ["Zapisy logowań i działań w panelu", "12 miesięcy"],
                ["Dane sesji zalogowanych urządzeń", "30 dni od wygaśnięcia sesji, nie dłużej niż 90 dni"],
                ["Dane kontaktowe osób upoważnionych", "czas trwania umowy, a po jej zakończeniu do upływu terminu przedawnienia roszczeń"],
                ["Faktury i dokumenty księgowe", "okres wymagany przepisami podatkowymi"],
              ],
            },
          },
          "Po zakończeniu współpracy wygaszamy wszystkie dane dostępowe do panelu. Na wniosek Klienta usuwamy materiały wcześniej.",
        ],
      },
      {
        naglowek: "6. Twoje prawa",
        tresc: [
          "Masz prawo do:",
          {
            lista: [
              "dostępu do swoich danych i otrzymania ich kopii,",
              "sprostowania danych nieprawidłowych lub niekompletnych,",
              "usunięcia danych,",
              "ograniczenia przetwarzania,",
              "przenoszenia danych,",
              "sprzeciwu wobec przetwarzania opartego na naszym uzasadnionym interesie.",
            ],
          },
          "Żeby skorzystać z któregokolwiek, napisz na kontakt@foodiemedia.pl. Odpowiadamy w ciągu miesiąca.",
          "Masz też prawo wnieść skargę do **Prezesa Urzędu Ochrony Danych Osobowych**, ul. Stawki 2, 00-193 Warszawa.",
        ],
      },
      {
        naglowek: "7. Czy podanie danych jest obowiązkowe",
        tresc: ["Podanie imienia, nazwiska i numeru telefonu jest dobrowolne, ale bez nich nie jesteśmy w stanie wydać dostępu do panelu ani przekazać danych logowania."],
      },
      {
        naglowek: "8. Automatyczne decyzje i profilowanie",
        tresc: [
          "Nie profilujemy Cię i nie podejmujemy wobec Ciebie decyzji wyłącznie w sposób zautomatyzowany na podstawie analizy Twoich danych.",
          "Panel zawiera mechanizm automatycznej akceptacji materiałów po upływie 72 godzin, opisany w regulaminie. Jest to uzgodniony umownie sposób liczenia terminu, a nie decyzja podejmowana na podstawie analizy danych osobowych.",
        ],
      },
      {
        naglowek: "9. Pliki cookies",
        tresc: [
          "Używamy wyłącznie plików niezbędnych do działania panelu: pliku utrzymującego zalogowanie oraz plików związanych z bezpieczeństwem sesji. Nie stosujemy cookies analitycznych ani marketingowych, dlatego nie prosimy o zgodę na ich użycie.",
        ],
      },
      {
        naglowek: "10. Zmiany polityki",
        tresc: [
          "Politykę możemy zmienić, gdy zmienią się funkcje panelu, dostawcy lub przepisy. O zmianie poinformujemy w panelu z co najmniej 14-dniowym wyprzedzeniem. Data u góry dokumentu zawsze wskazuje aktualną wersję.",
        ],
      },
    ],
  },
  bledy: {
    ogolny: "Coś poszło nie tak. Odśwież stronę, a jeśli to nie pomoże, napisz do swojego opiekuna.",
  },
} as const;

export type Copy = typeof copy;
